# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c39dc9eda1096e5908f5d3623329d139e738e2f60f478cd21a1d3d23c7132388
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embed_extra
defmodule E2e.EmbedExtraTest do
  use ExUnit.Case, async: false

  describe "embed_texts_batch" do
    test "embed_texts_batch" do
      {:ok, result} = Xberg.embed_texts_async(["Hello", "World"], "{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}")
    end
  end
end
