# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:faba9bd9cd6459916b35befc0016d7e4c4a5fff356d7aa478c51dd1ac966f022
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embedding_backend_management
defmodule E2e.EmbeddingBackendManagementTest do
  use ExUnit.Case, async: false

  describe "embedding_backends_clear" do
    test "embedding_backends_clear" do
      result = Kreuzberg.clear_embedding_backends()
    end
  end

  describe "embedding_backends_list" do
    test "embedding_backends_list" do
      result = Kreuzberg.list_embedding_backends()
    end
  end
end
