# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:52d810dddba1010b606994310ce2a05f1937641c736814d217688096779f4320
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: embed_extra
defmodule E2e.EmbedExtraTest do
  use ExUnit.Case, async: false

  describe "embed_texts_batch" do
    test "embed_texts_batch" do
      {:ok, result} = Xberg.embed_texts_async(["Hello", "World"], "{\"model\":{\"name\":\"balanced\",\"type\":\"preset\"}}")
    end
  end
end
