# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:93495e965e210d9c9496568d953da9966b0458b005882a1322aabdf15b34ce0c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: post_processor_management
defmodule E2e.PostProcessorManagementTest do
  use ExUnit.Case, async: false

  describe "post_processors_clear" do
    test "post_processors_clear" do
      result = Xberg.clear_post_processors()
    end
  end

  describe "post_processors_list" do
    test "post_processors_list" do
      result = Xberg.list_post_processors()
    end
  end
end
