# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6e273900ce19c7622b0762a1859860b5d4a3fd0209372543c5555415f48cc0a2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: registry
defmodule E2e.RegistryTest do
  use ExUnit.Case, async: false

  describe "list_document_extractors" do
    test "list_document_extractors" do
      result = Kreuzberg.list_document_extractors()
    end
  end

  describe "list_embedding_backends" do
    test "list_embedding_backends" do
      result = Kreuzberg.list_embedding_backends()
    end
  end

  describe "list_ocr_backends" do
    test "list_ocr_backends" do
      result = Kreuzberg.list_ocr_backends()
    end
  end

  describe "list_post_processors" do
    test "list_post_processors" do
      result = Kreuzberg.list_post_processors()
    end
  end

  describe "list_renderers" do
    test "list_renderers" do
      result = Kreuzberg.list_renderers()
    end
  end

  describe "list_validators" do
    test "list_validators" do
      result = Kreuzberg.list_validators()
    end
  end
end
