# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e939c65acd0b9087465d609f7d4a63fb1e21a6ea05b1bfeb8dc1b32b54a13cf6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: registry
defmodule E2e.RegistryTest do
  use ExUnit.Case, async: false

  describe "list_document_extractors" do
    test "list_document_extractors" do
      result = Kreuzberg.list_document_extractors()
    end
  end

  describe "list_embedding_backends" do
    test "list_embedding_backends" do
      result = Kreuzberg.list_embedding_backends()
    end
  end

  describe "list_ocr_backends" do
    test "list_ocr_backends" do
      result = Kreuzberg.list_ocr_backends()
    end
  end

  describe "list_post_processors" do
    test "list_post_processors" do
      result = Kreuzberg.list_post_processors()
    end
  end

  describe "list_renderers" do
    test "list_renderers" do
      result = Kreuzberg.list_renderers()
    end
  end

  describe "list_validators" do
    test "list_validators" do
      result = Kreuzberg.list_validators()
    end
  end
end
