# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e4a17520766145e761ea1662da07f7497a7f2fd19fcf9ecada67bc4a6ab85861
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: registry_operations
defmodule E2e.RegistryOperationsTest do
  use ExUnit.Case, async: false

  describe "extensions_docx" do
    test "extensions_docx" do
      {:ok, result} = Kreuzberg.get_extensions_for_mime("application/vnd.openxmlformats-officedocument.wordprocessingml.document")
    end
  end

  describe "extensions_html" do
    test "extensions_html" do
      {:ok, result} = Kreuzberg.get_extensions_for_mime("text/html")
    end
  end

  describe "extensions_pdf" do
    test "extensions_pdf" do
      {:ok, result} = Kreuzberg.get_extensions_for_mime("application/pdf")
    end
  end
end
