# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c2a3fd9729453c7020e8a1ed4d1ef626b5f48c2861b32bca702aef7a4b1fbe9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: registry_operations
defmodule E2e.RegistryOperationsTest do
  use ExUnit.Case, async: false

  describe "extensions_docx" do
    test "extensions_docx" do
      {:ok, result} = Kreuzberg.get_extensions_for_mime("application/vnd.openxmlformats-officedocument.wordprocessingml.document")
    end
  end

  describe "extensions_html" do
    test "extensions_html" do
      {:ok, result} = Kreuzberg.get_extensions_for_mime("text/html")
    end
  end

  describe "extensions_pdf" do
    test "extensions_pdf" do
      {:ok, result} = Kreuzberg.get_extensions_for_mime("application/pdf")
    end
  end
end
