# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2aa70876db291249caef7e2a16872fadb624b2104d7a088ca1880f8c5c3791ad
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# E2e tests for category: reranker_backend_management
defmodule E2e.RerankerBackendManagementTest do
  use ExUnit.Case, async: false

  describe "clear_reranker_backends" do
    test "clear_reranker_backends" do
      result = Kreuzberg.clear_reranker_backends()
    end
  end

  describe "list_reranker_backends" do
    test "list_reranker_backends" do
      result = Kreuzberg.list_reranker_backends()
    end
  end
end
