# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0336260e302c26ff585c4c04aceb3a97bacbca7a5eb642e1813c88dd18ea364d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# E2e tests for category: validator_management
defmodule E2e.ValidatorManagementTest do
  use ExUnit.Case, async: false

  describe "validators_clear" do
    test "validators_clear" do
      result = Kreuzberg.clear_validators()
    end
  end

  describe "validators_list" do
    test "validators_list" do
      result = Kreuzberg.list_validators()
    end
  end
end
