// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c39dc9eda1096e5908f5d3623329d139e738e2f60f478cd21a1d3d23c7132388
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Xberg;
using static Xberg.XbergConverter;

namespace Xberg
{
    /// <summary>E2e tests for category: async.</summary>
    public class AsyncTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public async Task Test_AsyncExtractBytes()
        {
            // Async extract_bytes call on PDF document
            var result = await XbergConverter.ExtractAsync(new ExtractionConfig { Data = "pdf/fake_memo.pdf", MimeType = "application/pdf" }, new ExtractionConfig());
    Assert.Equal("application/pdf", result.MimeType!.Trim());
    Assert.True(result.Content.Length >= 50, "expected length >= 50");

        }

        [Fact]
        public async Task Test_AsyncExtractBytesEmptyMime()
        {
            // extract_bytes empty MIME async
            await Assert.ThrowsAnyAsync<XbergException>(async () =>
            {
                await XbergConverter.ExtractAsync(new ExtractionConfig { Config = "{}", Data = "text/plain.txt", MimeType = "" }, new ExtractionConfig());
            });
        }

        [Fact]
        public async Task Test_AsyncExtractBytesInvalidMime()
        {
            // extract_bytes unsupported MIME async
            await Assert.ThrowsAnyAsync<XbergException>(async () =>
            {
                await XbergConverter.ExtractAsync(new ExtractionConfig { Config = "{}", Data = "text/plain.txt", MimeType = "application/x-nonexistent" }, new ExtractionConfig());
            });
        }


    }
}
