// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c39dc9eda1096e5908f5d3623329d139e738e2f60f478cd21a1d3d23c7132388
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Xberg;
using static Xberg.XbergConverter;

namespace Xberg
{
    /// <summary>E2e tests for category: batch.</summary>
    public class BatchTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public async Task Test_BatchBytesInvalidMime()
        {
            // batch_extract_bytes_sync invalid MIME
            var result = await XbergConverter.ExtractAsync(new ExtractionConfig { Items = new List<string> { "{\"content\":[72,101,108,108,111],\"mime_type\":\"application/x-nonexistent\"}" } }, new ExtractionConfig());

        }

        [Fact]
        public async Task Test_BatchExtractBytesHappy()
        {
            // batch_extract_bytes: happy path with mixed inputs
            var result = await XbergConverter.ExtractAsync(new ExtractionConfig { Items = new List<string> { "{\"content\":[72,101,108,108,111,44,32,119,111,114,108,100,33],\"mime_type\":\"text/plain\"}", "{\"content\":[60,104,116,109,108,62,60,98,111,100,121,62,84,101,115,116,60,47,98,111,100,121,62,60,47,104,116,109,108,62],\"mime_type\":\"text/html\"}" } }, new ExtractionConfig());
    Assert.True(result.Count >= 1, "expected at least 1 elements");

        }

        [Fact]
        public async Task Test_BatchExtractBytesMixedFormat()
        {
            // batch_extract_bytes: handles unsupported MIME gracefully
            var result = await XbergConverter.ExtractAsync(new ExtractionConfig { Items = new List<string> { "{\"content\":[80,68,70,32,112,108,97,99,101,104,111,108,100,101,114],\"mime_type\":\"application/x-unknown\"}" } }, new ExtractionConfig());

        }

        [Fact]
        public async Task Test_BatchExtractBytesSyncEmptyList()
        {
            // batch_extract_bytes_sync: empty batch
            var result = await XbergConverter.ExtractAsync(new ExtractionConfig { Items = new List<string> {  } }, new ExtractionConfig());
    Assert.Empty(result);

        }

        [Fact]
        public async Task Test_BatchExtractBytesSyncInvalidMime()
        {
            // batch_extract_bytes_sync: unsupported MIME
            var result = await XbergConverter.ExtractAsync(new ExtractionConfig { Items = new List<string> { "{\"content\":[100,97,116,97],\"mime_type\":\"application/x-unknown\"}" } }, new ExtractionConfig());

        }

        [Fact]
        public async Task Test_BatchFileAsyncBasic()
        {
            // Extract text from multiple files asynchronously
            var result = await XbergConverter.ExtractAsync(new ExtractionConfig { Paths = new List<string> { "{\"path\":\"pdf/fake_memo.pdf\"}", "{\"path\":\"text/fake_text.txt\"}" } }, new ExtractionConfig());

        }

        [Fact]
        public async Task Test_BatchFileAsyncNotFound()
        {
            // batch_extract_file async nonexistent
            var result = await XbergConverter.ExtractAsync(new ExtractionConfig { Paths = new List<string> { "{\"path\":\"/nonexistent/a.pdf\"}" } }, new ExtractionConfig());

        }

        [Fact]
        public async Task Test_BatchFileNotFound()
        {
            // batch_extract_file_sync nonexistent
            var result = await XbergConverter.ExtractAsync(new ExtractionConfig { Paths = new List<string> { "{\"path\":\"/nonexistent/a.pdf\"}", "{\"path\":\"/nonexistent/b.txt\"}" } }, new ExtractionConfig());

        }

        [Fact]
        public async Task Test_BatchFilePartial()
        {
            // batch_extract_file_sync mixed
            var result = await XbergConverter.ExtractAsync(new ExtractionConfig { Paths = new List<string> { "{\"path\":\"text/plain.txt\"}", "{\"path\":\"/nonexistent/missing.pdf\"}" } }, new ExtractionConfig());

        }

        [Fact]
        public async Task Test_BatchFileSyncBasic()
        {
            // Extract text from multiple files synchronously
            var result = await XbergConverter.ExtractAsync(new ExtractionConfig { Paths = new List<string> { "{\"path\":\"pdf/fake_memo.pdf\"}", "{\"path\":\"text/fake_text.txt\"}" } }, new ExtractionConfig());

        }


    }
}
