// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:eb5be1c33cb28fe9cd7339926a1508239529d634524a0fcd5f530dcb435666df
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Xunit;
using Xberg;
using static Xberg.XbergConverter;

namespace Xberg
{
    /// <summary>E2e tests for category: renderer_management.</summary>
    public class RendererManagementTests
    {
            private static readonly JsonSerializerOptions ConfigOptions = new() { Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) }, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault };

        [Fact]
        public void Test_RenderersClear()
        {
            // Clear all renderers and verify list is empty
            XbergConverter.ClearRenderers();
        }

        [Fact]
        public void Test_RenderersList()
        {
            // List all registered renderers
            var result = XbergConverter.ListRenderers();

        }


    }
}
