// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c39dc9eda1096e5908f5d3623329d139e738e2f60f478cd21a1d3d23c7132388
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractInput;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;

/** E2e tests for category: batch. */
public class BatchTest {

    @Test
    void testBatchBytesInvalidMime() throws Exception {
        // batch_extract_bytes_sync invalid MIME
        var input = JsonUtil.fromJson("{\"items\":[{\"content\":[72,101,108,108,111],\"mime_type\":\"application/x-nonexistent\"}]}", ExtractionConfig.class);

        var result = Xberg.extract(input, ExtractionConfig.builder().build());


    }


    @Test
    void testBatchExtractBytesHappy() throws Exception {
        // batch_extract_bytes: happy path with mixed inputs
        var input = JsonUtil.fromJson("{\"items\":[{\"content\":[72,101,108,108,111,44,32,119,111,114,108,100,33],\"mime_type\":\"text/plain\"},{\"content\":[60,104,116,109,108,62,60,98,111,100,121,62,84,101,115,116,60,47,98,111,100,121,62,60,47,104,116,109,108,62],\"mime_type\":\"text/html\"}]}", ExtractionConfig.class);

        var result = Xberg.extract(input, ExtractionConfig.builder().build());
assertTrue(result.size() >= 1, "expected at least 1 elements");

    }


    @Test
    void testBatchExtractBytesMixedFormat() throws Exception {
        // batch_extract_bytes: handles unsupported MIME gracefully
        var input = JsonUtil.fromJson("{\"items\":[{\"content\":[80,68,70,32,112,108,97,99,101,104,111,108,100,101,114],\"mime_type\":\"application/x-unknown\"}]}", ExtractionConfig.class);

        var result = Xberg.extract(input, ExtractionConfig.builder().build());


    }


    @Test
    void testBatchExtractBytesSyncEmptyList() throws Exception {
        // batch_extract_bytes_sync: empty batch
        var input = JsonUtil.fromJson("{\"items\":[]}", ExtractionConfig.class);

        var result = Xberg.extract(input, ExtractionConfig.builder().build());
assertEquals(0, result.size(), "expected exactly 0 elements");

    }


    @Test
    void testBatchExtractBytesSyncInvalidMime() throws Exception {
        // batch_extract_bytes_sync: unsupported MIME
        var input = JsonUtil.fromJson("{\"items\":[{\"content\":[100,97,116,97],\"mime_type\":\"application/x-unknown\"}]}", ExtractionConfig.class);

        var result = Xberg.extract(input, ExtractionConfig.builder().build());


    }


    @Test
    void testBatchFileAsyncBasic() throws Exception {
        // Extract text from multiple files asynchronously
        var input = JsonUtil.fromJson("{\"paths\":[{\"path\":\"pdf/fake_memo.pdf\"},{\"path\":\"text/fake_text.txt\"}]}", ExtractionConfig.class);

        var result = Xberg.extract(input, ExtractionConfig.builder().build());


    }


    @Test
    void testBatchFileAsyncNotFound() throws Exception {
        // batch_extract_file async nonexistent
        var input = JsonUtil.fromJson("{\"paths\":[{\"path\":\"/nonexistent/a.pdf\"}]}", ExtractionConfig.class);

        var result = Xberg.extract(input, ExtractionConfig.builder().build());


    }


    @Test
    void testBatchFileNotFound() throws Exception {
        // batch_extract_file_sync nonexistent
        var input = JsonUtil.fromJson("{\"paths\":[{\"path\":\"/nonexistent/a.pdf\"},{\"path\":\"/nonexistent/b.txt\"}]}", ExtractionConfig.class);

        var result = Xberg.extract(input, ExtractionConfig.builder().build());


    }


    @Test
    void testBatchFilePartial() throws Exception {
        // batch_extract_file_sync mixed
        var input = JsonUtil.fromJson("{\"paths\":[{\"path\":\"text/plain.txt\"},{\"path\":\"/nonexistent/missing.pdf\"}]}", ExtractionConfig.class);

        var result = Xberg.extract(input, ExtractionConfig.builder().build());


    }


    @Test
    void testBatchFileSyncBasic() throws Exception {
        // Extract text from multiple files synchronously
        var input = JsonUtil.fromJson("{\"paths\":[{\"path\":\"pdf/fake_memo.pdf\"},{\"path\":\"text/fake_text.txt\"}]}", ExtractionConfig.class);

        var result = Xberg.extract(input, ExtractionConfig.builder().build());


    }

}
