// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c39dc9eda1096e5908f5d3623329d139e738e2f60f478cd21a1d3d23c7132388
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;

/** E2e tests for category: detection. */
public class DetectionTest {

    @Test
    void testDetectMimeBytesHtml() throws Exception {
        // Detect HTML MIME from bytes
        var result = Xberg.detectMimeTypeFromBytes(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("html/html.html")));


    }


    @Test
    void testDetectMimeBytesPdf() throws Exception {
        // Detect PDF MIME type from bytes
        var result = Xberg.detectMimeTypeFromBytes(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("pdf/fake_memo.pdf")));


    }


    @Test
    void testDetectMimeBytesPng() throws Exception {
        // Detect PNG MIME type from bytes
        var result = Xberg.detectMimeTypeFromBytes(java.nio.file.Files.readAllBytes(java.nio.file.Path.of("images/test_hello_world.png")));


    }


    @Test
    void testGetExtensionsUnknownMime() throws Exception {
        // get_extensions unknown MIME
        // Wrap setup_lines + call_expr inside the lambda so error fixtures
        // catch failures at *any* step — including `<Type>.fromJson(...)`
        // calls that throw on malformed JSON (e.g. error fixtures with an
        // invalid enum value like `"purpose":"invalid-purpose"`). Mirrors
        // the C# `Assert.ThrowsAnyAsync(() => client.X(Type.FromJson(...)))`
        // pattern.
        assertThrows(Exception.class, () -> {
            Xberg.getExtensionsForMime("application/x-totally-unknown");
        });

    }

}
