// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:38239aba5298b05bb7627da7dd29f61167e18c420fcb64676bf355b0040d0a32
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package io.xberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.xberg.Xberg;
import io.xberg.ExtractionConfig;
import java.util.Optional;
import io.xberg.JsonUtil;

/** E2e tests for category: embedding_backend_management. */
public class EmbeddingBackendManagementTest {

    @Test
    void testEmbeddingBackendsClear() throws Exception {
        // Clear all embedding backends and verify list is empty
        Xberg.clearEmbeddingBackends();


    }


    @Test
    void testEmbeddingBackendsList() throws Exception {
        // List all registered embedding backends
        var result = Xberg.listEmbeddingBackends();


    }

}
