// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0336260e302c26ff585c4c04aceb3a97bacbca7a5eb642e1813c88dd18ea364d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
//! E2e tests for category: embed_extra

use kreuzberg::embed_texts;

#[test]
fn test_embed_texts_batch() {
    // Batch embed texts
    let texts_json: serde_json::Value = serde_json::from_str(r#"["Hello","World"]"#).unwrap();
    let texts = serde_json::from_value::<Vec<String>>(texts_json).unwrap();
    let config_json: serde_json::Value =
        serde_json::from_str(r#"{"model":{"name":"balanced","type":"preset"}}"#).unwrap();
    let config = serde_json::from_value(config_json).unwrap();
    let _ = embed_texts(texts, &config).expect("should succeed");
}
