// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:33cd355feac899a31cf1fb6f8a5313ff322dad245ad8c30d97279d07b63f4a51
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: reranker_backend_management

use xberg::{clear_reranker_backends, list_reranker_backends};

#[test]
fn test_clear_reranker_backends() {
    // Clear all reranker backends and verify list is empty
    let _ = clear_reranker_backends();
}

#[test]
fn test_list_reranker_backends() {
    // List all registered reranker backends
    let _ = list_reranker_backends();
}
