// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7b6093f244759948a70f40a504f7baff35f202ad22a2e3925f5b4946344cde9b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
//! E2e tests for category: tokenizer_backend_management

use xberg::{clear_tokenizer_backends, list_tokenizer_backends};

#[test]
fn test_tokenizer_backends_clear() {
    // Clear all tokenizer backends and verify list is empty
    let _ = clear_tokenizer_backends();
}

#[test]
fn test_tokenizer_backends_list() {
    // List all registered tokenizer backends
    let _ = list_tokenizer_backends();
}
