# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:76dabbbc48f44358b4e72324b0f3fb0ea5555b0846c36bab986b34e87c098baf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.BrowserBackend do
  @moduledoc "Browser backend used for JavaScript rendering."

  @typedoc "Browser backend used for JavaScript rendering."
  @type t :: :chromiumoxide | :native

  @chromiumoxide :chromiumoxide
  @native :native

  @doc "Existing Chromium/CDP backend powered by chromiumoxide."
  @spec chromiumoxide() :: t()
  def chromiumoxide, do: @chromiumoxide
  @doc "Crawlberg-owned native browser backend derived from Obscura."
  @spec native() :: t()
  def native, do: @native
end
