# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:38239aba5298b05bb7627da7dd29f61167e18c420fcb64676bf355b0040d0a32
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.CaptioningConfig do
  @moduledoc "Configuration for the VLM captioning post-processor."

  @typedoc "Configuration for the VLM captioning post-processor."
  @type t :: %__MODULE__{
          llm: map(),
          prompt: String.t() | nil,
          min_image_area: non_neg_integer()
        }

  defstruct llm: nil,
            prompt: nil,
            min_image_area: 0
end
