# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:38239aba5298b05bb7627da7dd29f61167e18c420fcb64676bf355b0040d0a32
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ChunkInfo do
  @moduledoc "Information about a single chunk."

  @typedoc "Information about a single chunk."
  @type t :: %__MODULE__{
          index: non_neg_integer(),
          pages: map(),
          estimated_time_ms: non_neg_integer()
        }

  defstruct index: 0,
            pages: nil,
            estimated_time_ms: 0
end
