# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eb5be1c33cb28fe9cd7339926a1508239529d634524a0fcd5f530dcb435666df
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ClassificationLabel do
  @moduledoc "A single label + confidence pair."

  @typedoc "A single label + confidence pair."
  @type t :: %__MODULE__{
  label: String.t() | nil,
  confidence: float() | nil
  }

  defstruct label: nil,
  confidence: nil
end
