# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:52d810dddba1010b606994310ce2a05f1937641c736814d217688096779f4320
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  @typedoc "JATS contributor with role."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          role: String.t() | nil
        }

  defstruct name: nil,
            role: nil
end
