# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:52d810dddba1010b606994310ce2a05f1937641c736814d217688096779f4320
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  @typedoc "dBASE field information."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          field_type: String.t() | nil
        }

  defstruct name: nil,
            field_type: nil
end
