# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:33cd355feac899a31cf1fb6f8a5313ff322dad245ad8c30d97279d07b63f4a51
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DiffHunk do
  @moduledoc "A single contiguous hunk in a unified diff."

  @typedoc "A single contiguous hunk in a unified diff."
  @type t :: %__MODULE__{
  from_line: non_neg_integer(),
  from_count: non_neg_integer(),
  to_line: non_neg_integer(),
  to_count: non_neg_integer(),
  lines: [String.t() | nil]
  }

  defstruct from_line: 0,
  from_count: 0,
  to_line: 0,
  to_count: 0,
  lines: []
end
