# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7d69f93c62f49996446ca8e109bc69aee242e943de2dc761a797a89f85d56f7c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.DiffLine do
  @moduledoc """
  A single line in a unified-diff hunk.

  Defined here (rather than only in `crate::diff`) so `RevisionDelta` can
  reference it unconditionally, without requiring the `diff` Cargo feature.
  `crate::diff` re-exports this type verbatim.
  """

  @typedoc "A single line in a unified-diff hunk."
  @type t :: term()

  @typedoc "Unchanged context line."
  @type context :: %{type: :context, value: String.t()}
  @typedoc "Line added in the \"after\" version."
  @type added :: %{type: :added, value: String.t()}
  @typedoc "Line removed from the \"before\" version."
  @type removed :: %{type: :removed, value: String.t()}
end
