# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:38239aba5298b05bb7627da7dd29f61167e18c420fcb64676bf355b0040d0a32
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Entity do
  @moduledoc "A single named entity detected in the extracted text."

  @typedoc "A single named entity detected in the extracted text."
  @type t :: %__MODULE__{
          category: String.t() | nil,
          text: String.t() | nil,
          start: non_neg_integer(),
          end: non_neg_integer(),
          confidence: float() | nil
        }

  defstruct category: :person,
            text: nil,
            start: 0,
            end: 0,
            confidence: nil
end
