# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0dfdfc675fa0466d5742def18462b27194b5262bca2a05f5d7a89010cf5bb3b0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExcelWorkbook do
  @moduledoc """
  Excel workbook representation.

  Contains all sheets from an Excel file (.xlsx, .xls, etc.) with
  extracted content and metadata.
  """

  @typedoc "Excel workbook representation."
  @type t :: %__MODULE__{
  sheets: [Xberg.ExcelSheet.t()],
  metadata: map(),
  revisions: [Xberg.DocumentRevision.t()] | nil
  }

  defstruct sheets: [],
  metadata: %{},
  revisions: nil
end
