# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:926a121ce8858da89e1c2dae78836bd02775ed955b144da6ce043a83737b8c26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ExtractionDiff do
  @moduledoc "The complete diff between two `ExtractedDocument` values."

  @typedoc "The complete diff between two `ExtractedDocument` values."
  @type t :: %__MODULE__{
  content_diff: [Xberg.DiffHunk.t()],
  tables_added: [Xberg.Table.t()],
  tables_removed: [Xberg.Table.t()],
  tables_changed: [Xberg.TableDiff.t()],
  metadata_changed: String.t() | nil,
  embedded_changes: Xberg.EmbeddedChanges.t()
  }

  defstruct content_diff: [],
  tables_added: [],
  tables_removed: [],
  tables_changed: [],
  metadata_changed: nil,
  embedded_changes: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
