# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:33cd355feac899a31cf1fb6f8a5313ff322dad245ad8c30d97279d07b63f4a51
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.FictionBookMetadata do
  @moduledoc "FictionBook (FB2) metadata."

  @typedoc "FictionBook (FB2) metadata."
  @type t :: %__MODULE__{
  genres: [String.t()],
  sequences: [String.t()],
  annotation: String.t() | nil
  }

  defstruct genres: [],
  sequences: [],
  annotation: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
