# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:38239aba5298b05bb7627da7dd29f61167e18c420fcb64676bf355b0040d0a32
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Footnote do
  @moduledoc "Footnote in Djot."

  @typedoc "Footnote in Djot."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          content: [map()]
        }

  defstruct label: nil,
            content: []
end
