# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a8a2fb5049e2e094c83b3ad2e0f6f13f62b4fea58f71c4a4f1e331a37b4cdec3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.Formula do
  @moduledoc """
  A mathematical formula detected and recognized in a document.

  Populated by the layout-guided formula pipeline: regions classified as
  `LayoutClass::Formula` are routed to the formula OCR task, which returns the
  LaTeX source for the region. The field is always present on
  [`ExtractedDocument`](super::extraction::ExtractedDocument) but only populated
  when the `layout-detection` feature is active and the document contains
  formula regions.
  """

  @typedoc "A mathematical formula detected and recognized in a document."
  @type t :: %__MODULE__{
          latex: String.t() | nil,
          bbox: Xberg.BoundingBox.t(),
          page: non_neg_integer()
        }

  defstruct latex: nil,
            bbox: nil,
            page: 0
end
