# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:93495e965e210d9c9496568d953da9966b0458b005882a1322aabdf15b34ce0c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.HeadingLevel do
  @moduledoc "A single heading in the hierarchy."

  @typedoc "A single heading in the hierarchy."
  @type t :: %__MODULE__{
  level: non_neg_integer(),
  text: String.t() | nil
  }

  defstruct level: 0,
  text: nil
end
