# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a8a2fb5049e2e094c83b3ad2e0f6f13f62b4fea58f71c4a4f1e331a37b4cdec3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ImageMetadataType do
  @moduledoc "Image element metadata."

  @typedoc "Image element metadata."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil,
          image_type: String.t() | nil
        }

  defstruct src: nil,
            alt: nil,
            title: nil,
            image_type: :data_uri
end
