# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d63e0283476bd8f41fd1b07ab7d0bbfde196679db404e32bcf4edb1a021f1f52
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.KeywordAlgorithm do
  @moduledoc "Keyword algorithm selection."

  @typedoc "Keyword algorithm selection."
  @type t :: :yake | :rake

  @yake :yake
  @rake :rake

  @doc "YAKE (Yet Another Keyword Extractor) - statistical approach"
  @spec yake() :: t()
  def yake, do: @yake
  @doc "RAKE (Rapid Automatic Keyword Extraction) - co-occurrence based"
  @spec rake() :: t()
  def rake, do: @rake
end
