# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:76dabbbc48f44358b4e72324b0f3fb0ea5555b0846c36bab986b34e87c098baf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.LinkMetadata do
  @moduledoc "Link element metadata."

  @typedoc "Link element metadata."
  @type t :: %__MODULE__{
  href: String.t() | nil,
  text: String.t() | nil,
  title: String.t() | nil,
  link_type: String.t() | nil,
  rel: [String.t()]
  }

  defstruct href: nil,
  text: nil,
  title: nil,
  link_type: :anchor,
  rel: []
end
