# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:49d7737c4c8395f019e87ea16ab3317aeda42281d98fd36f5ee4369a81b3e523
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.MultidocInput do
  @moduledoc "Input signals for multi-document boundary detection."

  @typedoc "Input signals for multi-document boundary detection."
  @type t :: %__MODULE__{
          page_count: non_neg_integer(),
          pages: [Xberg.PageSignals.t()]
        }

  defstruct page_count: 0,
            pages: []
end
