# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d63e0283476bd8f41fd1b07ab7d0bbfde196679db404e32bcf4edb1a021f1f52
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.NerBackendKind do
  @moduledoc "NER backend selector."

  @typedoc "NER backend selector."
  @type t :: :onnx | :llm

  @onnx :onnx
  @llm :llm

  @doc "`xberg-gliner` ONNX inference. Requires `ner-onnx` feature. Models download lazily from `xberg-io/gliner-models`."
  @spec onnx() :: t()
  def onnx, do: @onnx
  @doc "liter-llm zero-shot NER via structured-output prompts. Requires `ner-llm` feature. Useful when domain-specific categories outstrip the ONNX taxonomy."
  @spec llm() :: t()
  def llm, do: @llm
end
