# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0dfdfc675fa0466d5742def18462b27194b5262bca2a05f5d7a89010cf5bb3b0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrPipelineConfig do
  @moduledoc """
  Multi-backend OCR pipeline with quality-based fallback.

  Backends are tried in priority order (highest first). After each backend
  produces output, quality is evaluated. If it meets `quality_thresholds.pipeline_min_quality`,
  the result is accepted. Otherwise the next backend is tried.
  """

  @typedoc "Multi-backend OCR pipeline with quality-based fallback."
  @type t :: %__MODULE__{
  stages: [Xberg.OcrPipelineStage.t()],
  quality_thresholds: Xberg.OcrQualityThresholds.t()
  }

  defstruct stages: [],
  quality_thresholds: nil
end
