# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7d69f93c62f49996446ca8e109bc69aee242e943de2dc761a797a89f85d56f7c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrMetadata do
  @moduledoc """
  OCR processing metadata.

  Captures information about OCR processing configuration and results.
  """

  @typedoc "OCR processing metadata."
  @type t :: %__MODULE__{
          language: String.t() | nil,
          psm: integer(),
          output_format: String.t() | nil,
          table_count: non_neg_integer(),
          table_rows: non_neg_integer() | nil,
          table_cols: non_neg_integer() | nil
        }

  defstruct language: nil,
            psm: 0,
            output_format: nil,
            table_count: 0,
            table_rows: nil,
            table_cols: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
