# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0dfdfc675fa0466d5742def18462b27194b5262bca2a05f5d7a89010cf5bb3b0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.OcrPipelineStage do
  @moduledoc "A single backend stage in the OCR pipeline."

  @typedoc "A single backend stage in the OCR pipeline."
  @type t :: %__MODULE__{
  backend: String.t() | nil,
  priority: non_neg_integer(),
  language: [String.t()] | nil,
  tesseract_config: Xberg.TesseractConfig.t() | nil,
  paddle_ocr_config: String.t() | nil,
  vlm_config: Xberg.LlmConfig.t() | nil,
  backend_options: String.t() | nil
  }

  defstruct backend: nil,
  priority: 0,
  language: nil,
  tesseract_config: nil,
  paddle_ocr_config: nil,
  vlm_config: nil,
  backend_options: nil
end
