# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a8a2fb5049e2e094c83b3ad2e0f6f13f62b4fea58f71c4a4f1e331a37b4cdec3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PatternMatch do
  @moduledoc "One detected PII span in the input text."

  @typedoc "One detected PII span in the input text."
  @type t :: %__MODULE__{
          start: non_neg_integer(),
          end: non_neg_integer(),
          category: String.t() | nil,
          text: String.t() | nil
        }

  defstruct start: 0,
            end: 0,
            category: :email,
            text: nil
end
