# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7b6093f244759948a70f40a504f7baff35f202ad22a2e3925f5b4946344cde9b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PdfAnnotation do
  @moduledoc "A PDF annotation extracted from a document page."

  @typedoc "A PDF annotation extracted from a document page."
  @type t :: %__MODULE__{
  annotation_type: String.t() | nil,
  content: String.t() | nil,
  page_number: non_neg_integer(),
  bounding_box: Xberg.BoundingBox.t() | nil
  }

  defstruct annotation_type: :text,
  content: nil,
  page_number: 0,
  bounding_box: nil
end
