# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d63e0283476bd8f41fd1b07ab7d0bbfde196679db404e32bcf4edb1a021f1f52
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PiiCategory do
  @moduledoc "PII categories the pattern engine recognises."

  @typedoc "PII categories the pattern engine recognises."
  @type t :: term()

  @typedoc "Email address (e.g. `user@example.com`)."
  @type email :: :email
  @typedoc "Phone number in any common format."
  @type phone :: :phone
  @typedoc "US Social Security Number."
  @type ssn :: :ssn
  @typedoc "Payment card number (Visa, Mastercard, Amex, etc.)."
  @type credit_card :: :credit_card
  @typedoc "Postal / ZIP code."
  @type postal_code :: :postal_code
  @typedoc "IPv4 or IPv6 address."
  @type ip_address :: :ip_address
  @typedoc "International Bank Account Number."
  @type iban :: :iban
  @typedoc "SWIFT / BIC bank identifier code."
  @type swift_bic :: :swift_bic
  @typedoc "Date of birth."
  @type date_of_birth :: :date_of_birth
  @typedoc "Person name, surfaced by the optional NER backend."
  @type person :: :person
  @typedoc "Organization name, surfaced by the optional NER backend."
  @type organization :: :organization
  @typedoc "Location, surfaced by the optional NER backend."
  @type location :: :location
  @typedoc "Caller-supplied custom category (e.g. internal employee IDs)."
  @type custom :: %{type: :custom, value: String.t()}
end
