# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:49d7737c4c8395f019e87ea16ab3317aeda42281d98fd36f5ee4369a81b3e523
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PresetSample do
  @moduledoc "Pointer to a sample input + its reference output bundled with the preset."

  @typedoc "Pointer to a sample input + its reference output bundled with the preset."
  @type t :: %__MODULE__{
          input_path: String.t() | nil,
          output_path: String.t() | nil
        }

  defstruct input_path: nil,
            output_path: nil
end
