# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7b6093f244759948a70f40a504f7baff35f202ad22a2e3925f5b4946344cde9b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PresetCategory do
  @moduledoc "High-level category used to group presets in the registry UI."

  @typedoc "High-level category used to group presets in the registry UI."
  @type t :: :finance | :identity | :legal | :logistics | :medical | :hr | :other

  @finance :finance
  @identity :identity
  @legal :legal
  @logistics :logistics
  @medical :medical
  @hr :hr
  @other :other

  @doc "Invoices, receipts, statements, purchase orders, W-9."
  @spec finance() :: t()
  def finance, do: @finance
  @doc "Passports, drivers licenses, insurance cards."
  @spec identity() :: t()
  def identity, do: @identity
  @doc "Contracts, NDAs, agreements."
  @spec legal() :: t()
  def legal, do: @legal
  @doc "Bills of lading, customs declarations, packing lists."
  @spec logistics() :: t()
  def logistics, do: @logistics
  @doc "Clinical records, lab reports."
  @spec medical() :: t()
  def medical, do: @medical
  @doc "Pay stubs, resumes, employment offers."
  @spec hr() :: t()
  def hr, do: @hr
  @doc "Catch-all for documents that don't fit the other categories."
  @spec other() :: t()
  def other, do: @other
end
