# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7d69f93c62f49996446ca8e109bc69aee242e943de2dc761a797a89f85d56f7c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.PresetSample do
  @moduledoc "Pointer to a sample input + its reference output bundled with the preset."

  @typedoc "Pointer to a sample input + its reference output bundled with the preset."
  @type t :: %__MODULE__{
          input_path: String.t() | nil,
          output_path: String.t() | nil
        }

  defstruct input_path: nil,
            output_path: nil
end
