# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:76dabbbc48f44358b4e72324b0f3fb0ea5555b0846c36bab986b34e87c098baf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.ProcessingWarning do
  @moduledoc """
  A non-fatal warning from a processing pipeline stage.

  Captures errors from optional features that don't prevent extraction
  but may indicate degraded results.
  """

  @typedoc "A non-fatal warning from a processing pipeline stage."
  @type t :: %__MODULE__{
  source: String.t() | nil,
  message: String.t() | nil
  }

  defstruct source: nil,
  message: nil
end
