# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eb5be1c33cb28fe9cd7339926a1508239529d634524a0fcd5f530dcb435666df
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.QrCode do
  @moduledoc "One QR code decoded from an extracted image."

  @typedoc "One QR code decoded from an extracted image."
  @type t :: %__MODULE__{
  payload: String.t() | nil,
  confidence: float() | nil,
  bbox: Xberg.QrBoundingBox.t() | nil
  }

  defstruct payload: nil,
  confidence: nil,
  bbox: nil
end
