# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7d69f93c62f49996446ca8e109bc69aee242e943de2dc761a797a89f85d56f7c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.RakeParams do
  @moduledoc "RAKE-specific parameters."

  @typedoc "RAKE-specific parameters."
  @type t :: %__MODULE__{
          min_word_length: non_neg_integer(),
          max_words_per_phrase: non_neg_integer()
        }

  defstruct min_word_length: 1,
            max_words_per_phrase: 3

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
