# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:926a121ce8858da89e1c2dae78836bd02775ed955b144da6ce043a83737b8c26
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.SitemapUrl do
  @moduledoc "A URL entry from a sitemap."

  @typedoc "A URL entry from a sitemap."
  @type t :: %__MODULE__{
  url: String.t() | nil,
  lastmod: String.t() | nil,
  changefreq: String.t() | nil,
  priority: String.t() | nil
  }

  defstruct url: nil,
  lastmod: nil,
  changefreq: nil,
  priority: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
