# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0dfdfc675fa0466d5742def18462b27194b5262bca2a05f5d7a89010cf5bb3b0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TableGrid do
  @moduledoc """
  Structured table grid with cell-level metadata.

  Stores row/column dimensions and a flat list of cells with position info.
  """

  @typedoc "Structured table grid with cell-level metadata."
  @type t :: %__MODULE__{
  rows: non_neg_integer(),
  cols: non_neg_integer(),
  cells: [Xberg.GridCell.t()]
  }

  defstruct rows: 0,
  cols: 0,
  cells: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
