# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:38239aba5298b05bb7627da7dd29f61167e18c420fcb64676bf355b0040d0a32
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TableDiff do
  @moduledoc "Cell-level changes for a pair of tables that share the same index."

  @typedoc "Cell-level changes for a pair of tables that share the same index."
  @type t :: %__MODULE__{
          from_index: non_neg_integer(),
          to_index: non_neg_integer(),
          cell_changes: [map()]
        }

  defstruct from_index: 0,
            to_index: 0,
            cell_changes: []
end
