# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0dfdfc675fa0466d5742def18462b27194b5262bca2a05f5d7a89010cf5bb3b0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TableDiff do
  @moduledoc "Cell-level changes for a pair of tables that share the same index."

  @typedoc "Cell-level changes for a pair of tables that share the same index."
  @type t :: %__MODULE__{
  from_index: non_neg_integer(),
  to_index: non_neg_integer(),
  cell_changes: [Xberg.CellChange.t()]
  }

  defstruct from_index: 0,
  to_index: 0,
  cell_changes: []
end
