# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:93495e965e210d9c9496568d953da9966b0458b005882a1322aabdf15b34ce0c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TokenCounter do
  @moduledoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."

  alias Xberg.Native
  defstruct [:ref]

  @typedoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Build a default instance."
  @spec new() :: t()
  def new do
    %__MODULE__{ref: Native.tokencounter_new()}
  end
  def default() do
    ref = Native.tokencounter_new()
    %__MODULE__{ref: ref}
  end
end
