# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0dfdfc675fa0466d5742def18462b27194b5262bca2a05f5d7a89010cf5bb3b0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TokenCounter do
  @moduledoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."

  alias Xberg.Native
  defstruct [:ref]

  @typedoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Build a default instance."
  @spec new() :: t()
  def new do
    %__MODULE__{ref: Native.tokencounter_new()}
  end
  def default() do
    ref = Native.tokencounter_new()
    %__MODULE__{ref: ref}
  end
end
