# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:52d810dddba1010b606994310ce2a05f1937641c736814d217688096779f4320
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TokenReductionOptions do
  @moduledoc "Token reduction configuration."

  @typedoc "Token reduction configuration."
  @type t :: %__MODULE__{
          mode: String.t() | nil,
          preserve_important_words: boolean()
        }

  defstruct mode: nil,
            preserve_important_words: true

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
