# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:76dabbbc48f44358b4e72324b0f3fb0ea5555b0846c36bab986b34e87c098baf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Xberg.TreeSitterProcessConfig do
  @moduledoc """
  Processing options for tree-sitter code analysis.

  Controls which analysis features are enabled when extracting code files.
  """

  @typedoc "Processing options for tree-sitter code analysis."
  @type t :: %__MODULE__{
  structure: boolean(),
  imports: boolean(),
  exports: boolean(),
  comments: boolean(),
  docstrings: boolean(),
  symbols: boolean(),
  diagnostics: boolean(),
  chunk_max_size: non_neg_integer() | nil,
  content_mode: String.t() | nil
  }

  defstruct structure: true,
  imports: true,
  exports: true,
  comments: false,
  docstrings: false,
  symbols: false,
  diagnostics: false,
  chunk_max_size: nil,
  content_mode: :chunks

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
    |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
