<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c39dc9eda1096e5908f5d3623329d139e738e2f60f478cd21a1d3d23c7132388
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: document_extractor_management. */
final class DocumentExtractorManagementTest extends TestCase
{

    /** Clear all document extractors and verify list is empty */
    public function test_document_extractors_clear(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::clearDocumentExtractors();


    }


    /** List all registered document extractors */
    public function test_extractors_list(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listDocumentExtractors(["setup" => ["lazy_init_required" => ["init_action" => "extract_file_sync", "init_data" => ["create_temp_file" => true, "temp_file_content" => "%PDF-1.4\n%EOF\n", "temp_file_name" => "test.pdf"], "languages" => ["go"]]]]);


    }

}
