<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:38239aba5298b05bb7627da7dd29f61167e18c420fcb64676bf355b0040d0a32
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: embed_async_pending. */
final class EmbedAsyncPendingTest extends TestCase
{

    /** embed_texts_async: empty text list */
    public function test_embed_texts_async_empty_input(): void
    {
        $config = \Xberg\EmbeddingConfig::from_json(json_encode(["model" => ["name" => "balanced", "type" => "preset"]]));
        $result = Xberg::embedTextsAsync([], $config);

        $this->assertCount(0, $result);

    }


    /** embed_texts_async: basic async embedding */
    public function test_embed_texts_async_happy(): void
    {
        $config = \Xberg\EmbeddingConfig::from_json(json_encode(["model" => ["name" => "balanced", "type" => "preset"]]));
        $result = Xberg::embedTextsAsync(["First", "Second"], $config);

        $this->assertGreaterThanOrEqual(2, count($result));

    }


    /** embed_texts_async: preset override */
    public function test_embed_texts_async_preset_switch(): void
    {
        $config = \Xberg\EmbeddingConfig::from_json(json_encode(["model" => ["name" => "balanced", "type" => "preset"]]));
        $this->expectNotToPerformAssertions();
        $result = Xberg::embedTextsAsync(["Text"], $config);


    }

}
