<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fa49f061b4922ae545a884b3557c72331bc9acf91f2b03d4dfc68363dc9f62b9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Kreuzberg\E2e;

use PHPUnit\Framework\TestCase;
use Kreuzberg\Kreuzberg;
use Kreuzberg\EmbeddingConfig;

/** E2e tests for category: embed_extra. */
final class EmbedExtraTest extends TestCase
{

    /** Batch embed texts */
    public function test_embed_texts_batch(): void
    {
        $config = \Kreuzberg\EmbeddingConfig::from_json(json_encode(["model" => ["name" => "balanced", "type" => "preset"]]));
        $this->expectNotToPerformAssertions();
        $result = Kreuzberg::embedTextsAsync(["Hello", "World"], $config);


    }

}
