<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:52d810dddba1010b606994310ce2a05f1937641c736814d217688096779f4320
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code


declare(strict_types=1);

namespace Xberg\E2e;

use PHPUnit\Framework\TestCase;
use Xberg\Xberg;
use Xberg\ExtractionConfig;

/** E2e tests for category: reranker_backend_management. */
final class RerankerBackendManagementTest extends TestCase
{

    /** Clear all reranker backends and verify list is empty */
    public function test_clear_reranker_backends(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::clearRerankerBackends();


    }


    /** List all registered reranker backends */
    public function test_list_reranker_backends(): void
    {
        $this->expectNotToPerformAssertions();
        $result = Xberg::listRerankerBackends();


    }

}
