// Generated by alef. Do not edit by hand.
// alef:hash:2aa70876db291249caef7e2a16872fadb624b2104d7a088ca1880f8c5c3791ad

package dev.kreuzberg

/// Bridge adapter for IEmbeddingBackend implementations.
///
/// Wraps a user-supplied IEmbeddingBackend instance and delegates all method calls.
/// This adapter is used internally by the trait bridge registration layer to ensure
/// proper handling of impl instances through JNI boundaries.
internal class EmbeddingBackendAdapter(private val impl: IEmbeddingBackend) : IEmbeddingBackend {
    // Delegate all interface methods to the wrapped implementation
    override fun name(): String = impl.name()

    override fun version(): String = impl.version()

    override fun initialize() = impl.initialize()

    override fun shutdown() = impl.shutdown()

    override fun description(): String = impl.description()

    override fun author(): String = impl.author()

    override fun dimensions(): Long {
        return impl.dimensions()
    }

    override suspend fun embed(texts: List<String>): List<List<Float>> {
        return impl.embed(texts)
    }


}
