// Generated by alef. Do not edit by hand.
// alef:hash:4c69455352c6694c6639030ae0ef9d405ca032b08d85d13bed84086fcdf60c8d
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
)

package dev.kreuzberg

/** EPUB metadata (Dublin Core extensions). */
data class EpubMetadata(
    /** Dublin Core `coverage` field (geographic or temporal scope). */
    val coverage: String? = null,
    /** Dublin Core `format` field (media type of the resource). */
    val dcFormat: String? = null,
    /** Dublin Core `relation` field (related resource identifier). */
    val relation: String? = null,
    /** Dublin Core `source` field (origin resource identifier). */
    val source: String? = null,
    /** Dublin Core `type` field (nature or genre of the resource). */
    val dcType: String? = null,
    /** Path or identifier of the cover image within the EPUB container. */
    val coverImage: String? = null,
)
