// Generated by alef. Do not edit by hand.
// alef:hash:c26185e7af68ca4756f10e088470f87071eb21785e05d75acd73c4ee0d7abef9
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
)

package dev.kreuzberg

/** Rotation information for an OCR element. */
data class OcrRotation(
    /** Rotation angle in degrees (0, 90, 180, 270 for PaddleOCR). */
    val angleDegrees: Double,
    /** Confidence score for the rotation detection. */
    val confidence: Double? = null,
)
