// Generated by alef. Do not edit by hand.
// alef:hash:cb855b5d14d74df904faec363ef477bfae87c4666396e9baad55d6044c6a4605
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

/** One detected PII span in the input text. */
data class PatternMatch(
    /** Inclusive byte-offset start of the match in the source text. */
    val start: Long,
    /** Exclusive byte-offset end of the match. */
    val end: Long,
    /** Category the match belongs to. */
    val category: PiiCategory,
    /**
     * Matched substring (owned copy — pattern engine returns owned data so the
     * caller can free the original text if needed before replacement).
     */
    val text: String,
)
