// Generated by alef. Do not edit by hand.
// alef:hash:5c2a3fd9729453c7020e8a1ed4d1ef626b5f48c2861b32bca702aef7a4b1fbe9

package dev.kreuzberg

object RendererBridge {
    private val registered = mutableMapOf<String, IRenderer>()

    fun register(impl: IRenderer): Unit {
        val name = impl.name()
        registered[name] = impl
        KreuzbergBridge.nativeRegisterRenderer(impl)
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        KreuzbergBridge.nativeUnregisterRenderer(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        KreuzbergBridge.nativeClearRenderers()
    }

    fun getAll(): Map<String, IRenderer> = registered.toMap()
}
