// Generated by alef. Do not edit by hand.
// alef:hash:6e273900ce19c7622b0762a1859860b5d4a3fd0209372543c5555415f48cc0a2

package dev.kreuzberg

/// Bridge adapter for IRenderer implementations.
///
/// Wraps a user-supplied IRenderer instance and delegates all method calls.
/// This adapter is used internally by the trait bridge registration layer to ensure
/// proper handling of impl instances through JNI boundaries.
internal class RendererAdapter(private val impl: IRenderer) : IRenderer {
    // Delegate all interface methods to the wrapped implementation
    override fun name(): String = impl.name()

    override fun version(): String = impl.version()

    override fun initialize() = impl.initialize()

    override fun shutdown() = impl.shutdown()

    override fun description(): String = impl.description()

    override fun author(): String = impl.author()


}
