// Generated by alef. Do not edit by hand.
// alef:hash:e939c65acd0b9087465d609f7d4a63fb1e21a6ea05b1bfeb8dc1b32b54a13cf6
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
)

package dev.kreuzberg

/**
 * Inline text annotation — byte-range based formatting and links.
 *
 * Annotations reference byte offsets into the node's text content,
 * enabling precise identification of formatted regions.
 */
data class TextAnnotation(
    /** Start byte offset in the node's text content (inclusive). */
    val start: Int,
    /** End byte offset in the node's text content (exclusive). */
    val end: Int,
    /** Annotation type. */
    @field:com.fasterxml.jackson.databind.annotation.JsonSerialize(`as` = AnnotationKind::class)
    val kind: AnnotationKind,
)
