// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:287fad381b3957c7a43d86285d13b15d426626ead595e8992131a4cf4fbe6bda
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: ocr_backend_management.
final class OcrBackendManagementTests: XCTestCase {
    func testOcrBackendsClear() throws {
        // Clear all OCR backends and verify list is empty
        let result = try Kreuzberg.clearOcrBackends()
    }

    func testOcrBackendsList() throws {
        // List all registered OCR backends
        let result = try Kreuzberg.listOcrBackends()
    }

    func testOcrBackendsUnregister() throws {
        // Unregister nonexistent OCR backend gracefully
        let result = try Kreuzberg.unregisterOcrBackend(name: "nonexistent-backend-xyz")
    }

}
