// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5f6a515f4cee741e840244242f9d162610a0d8a3fcdf086410779e59b2395d39
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Kreuzberg
import RustBridge

/// E2e tests for category: post_processor_management.
final class PostProcessorManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
    }

    func testPostProcessorsClear() throws {
        // Clear all post-processors and verify list is empty
        let result = try Kreuzberg.clearPostProcessors()
    }

    func testPostProcessorsList() throws {
        // List all registered post-processors
        let result = try Kreuzberg.listPostProcessors()
    }

}
