// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ecec728f4d5a11b69b4359bebc75a123561e4b20646050df54013f498614b58b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right.
/// </summary>
public sealed class BBox
{
    [JsonPropertyName("x1")]
    public float X1 { get; set; } = 0.0f;

    [JsonPropertyName("y1")]
    public float Y1 { get; set; } = 0.0f;

    [JsonPropertyName("x2")]
    public float X2 { get; set; } = 0.0f;

    [JsonPropertyName("y2")]
    public float Y2 { get; set; } = 0.0f;

}
