// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fd2396b78afa21f4b4cf259f7d6f4efc65190d98ad50e1188814f9da25f7d59e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Content layer classification for document nodes.
///
/// Replaces separate body/furniture arrays with per-node granularity.
/// </summary>
public enum ContentLayer
{
    /// <summary>
    /// Main document body content.
    /// </summary>
    [JsonPropertyName("body")]
    Body,
    /// <summary>
    /// Page/section header (running header).
    /// </summary>
    [JsonPropertyName("header")]
    Header,
    /// <summary>
    /// Page/section footer (running footer).
    /// </summary>
    [JsonPropertyName("footer")]
    Footer,
    /// <summary>
    /// Footnote content.
    /// </summary>
    [JsonPropertyName("footnote")]
    Footnote,
}
