// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:257a3bba9c7b9a1276a420cee4f3de681bc977065ab15ae83aba3416eb7ca3f2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Image element in Djot.
/// </summary>
public sealed class DjotImage
{
    /// <summary>
    /// Image source URL or path
    /// </summary>
    [JsonPropertyName("src")]
    public string Src { get; set; } = "";

    /// <summary>
    /// Alternative text
    /// </summary>
    [JsonPropertyName("alt")]
    public string Alt { get; set; } = "";

    /// <summary>
    /// Optional title
    /// </summary>
    [JsonPropertyName("title")]
    public string? Title { get; set; } = null;

    /// <summary>
    /// Element attributes
    /// </summary>
    [JsonPropertyName("attributes")]
    public string? Attributes { get; set; } = null;

}
