// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1522e04db9d0ca941a514176561093577255f7da64c856f3b22b489352d09774
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Error metadata (for batch operations).
/// </summary>
public sealed class ErrorMetadata
{
    [JsonPropertyName("error_type")]
    public string ErrorType { get; set; } = "";

    [JsonPropertyName("message")]
    public string Message { get; set; } = "";

}
