// This file is auto-generated by alef. DO NOT EDIT.
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

[JsonConverter(typeof(JsonStringEnumConverter))]
public enum FracType
{
    [JsonPropertyName("bar")]
    Bar, [JsonPropertyName("nobar")]
    NoBar, [JsonPropertyName("linear")]
    Linear, [JsonPropertyName("skewed")]
    Skewed,
}
