// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:7feddbe8eb60b6d7f1a211b23c72bf16a702e1d50dec1712ab561b3d3746f3b1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A single heading in the hierarchy.
/// </summary>
public sealed class HeadingLevel
{
    /// <summary>
    /// Heading depth (1 = h1, 2 = h2, etc.)
    /// </summary>
    [JsonPropertyName("level")]
    public byte Level { get; set; } = 0;

    /// <summary>
    /// The text content of the heading.
    /// </summary>
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

}
