// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8245c4d42eb74c31589758f0474848086016b9949447d30f03a89524c460d818
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class HeaderFooter
{
    [JsonPropertyName("paragraphs")]
    public List<string> Paragraphs { get; set; } = [];

    [JsonPropertyName("tables")]
    public List<string> Tables { get; set; } = [];

    [JsonPropertyName("header_type")]
    public string HeaderType { get; set; } = "";

}
