// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6670d4cd1c8a3e683661b24f170a3be48aa3dcec60f1eee5f23694e2b56fdd47
#nullable enable

using System;

namespace Kreuzberg;

public class ImageProcessingException : KreuzbergErrorException
{
    public ImageProcessingException(string message) : base(message) { }

    public ImageProcessingException(string message, Exception innerException) : base(message, innerException) { }
}
