// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1e76f851164182cee6be39ea7bd537fe5e636e056f07b1ac9047683168c541a2
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// A file system or I/O operation failed. These errors always bubble up unchanged.
/// </summary>
public class IoException : KreuzbergErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
