// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c64262b1dd7f5069d63c70acd28889b943b52fa2a3d45c254aa238aeda4c0005
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System.Text.Json.Serialization;

using System;
using System.Text.Json;

namespace Kreuzberg;

/// <summary>
/// Keyword algorithm selection.
/// </summary>
public enum KeywordAlgorithm
{
    /// <summary>
    /// YAKE (Yet Another Keyword Extractor) - statistical approach
    /// </summary>
    [JsonPropertyName("yake")]
    Yake,
    /// <summary>
    /// RAKE (Rapid Automatic Keyword Extraction) - co-occurrence based
    /// </summary>
    [JsonPropertyName("rake")]
    Rake,
}
