// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a529f31e8b3bd8b3ae23818bb260c1f6505de717c3462cd09dcea4b6ee71b52d
#nullable enable

using System;

namespace Kreuzberg;

public class MissingDependencyException : KreuzbergErrorException
{
    public MissingDependencyException(string message) : base(message) { }

    public MissingDependencyException(string message, Exception innerException) : base(message, innerException) { }
}
