// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e939c65acd0b9087465d609f7d4a63fb1e21a6ea05b1bfeb8dc1b32b54a13cf6
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// An OCR engine returned an error or produced unusable output.
/// </summary>
public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
