// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fa49f061b4922ae545a884b3557c72331bc9acf91f2b03d4dfc68363dc9f62b9
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// An OCR engine returned an error or produced unusable output.
/// </summary>
public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
