// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4c69455352c6694c6639030ae0ef9d405ca032b08d85d13bed84086fcdf60c8d
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// An OCR engine returned an error or produced unusable output.
/// </summary>
public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
