// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5c2a3fd9729453c7020e8a1ed4d1ef626b5f48c2861b32bca702aef7a4b1fbe9
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// Document parsing failed (e.g. corrupt file, unsupported format feature).
/// </summary>
public class ParsingException : KreuzbergErrorException
{
    public ParsingException(string message) : base(message) { }

    public ParsingException(string message, Exception innerException) : base(message, innerException) { }
}
