// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fa49f061b4922ae545a884b3557c72331bc9acf91f2b03d4dfc68363dc9f62b9
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// PDF analysis step failed (only when `heuristics-pdf` feature is active).
/// </summary>
public class PdfAnalysisErrorException : HeuristicsErrorException
{
    public PdfAnalysisErrorException(string message) : base(message) { }

    public PdfAnalysisErrorException(string message, Exception innerException) : base(message, innerException) { }
}
