// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fa49f061b4922ae545a884b3557c72331bc9acf91f2b03d4dfc68363dc9f62b9
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// The reranker model or reranking pipeline returned an error.
///
/// Since v5.0.0.
/// </summary>
public class RerankingException : KreuzbergErrorException
{
    public RerankingException(string message) : base(message) { }

    public RerankingException(string message, Exception innerException) : base(message, innerException) { }
}
