// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:4c69455352c6694c6639030ae0ef9d405ca032b08d85d13bed84086fcdf60c8d
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// The reranker model or reranking pipeline returned an error.
///
/// Since v5.0.0.
/// </summary>
public class RerankingException : KreuzbergErrorException
{
    public RerankingException(string message) : base(message) { }

    public RerankingException(string message, Exception innerException) : base(message, innerException) { }
}
