// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2aa70876db291249caef7e2a16872fadb624b2104d7a088ca1880f8c5c3791ad
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// The reranker model or reranking pipeline returned an error.
///
/// Since v5.0.0.
/// </summary>
public class RerankingException : KreuzbergErrorException
{
    public RerankingException(string message) : base(message) { }

    public RerankingException(string message, Exception innerException) : base(message, innerException) { }
}
