// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1e76f851164182cee6be39ea7bd537fe5e636e056f07b1ac9047683168c541a2
#nullable enable

using System;

namespace Kreuzberg;

/// <summary>
/// Audio/video transcription failed.
/// </summary>
public class TranscriptionException : KreuzbergErrorException
{
    public TranscriptionException(string message) : base(message) { }

    public TranscriptionException(string message, Exception innerException) : base(message, innerException) { }
}
