// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c39dc9eda1096e5908f5d3623329d139e738e2f60f478cd21a1d3d23c7132388
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: post_processor_management.
final class PostProcessorManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
    }

    func testPostProcessorsClear() throws {
        // Clear all post-processors and verify list is empty
        let result = try Xberg.clearPostProcessors()
    }

    func testPostProcessorsList() throws {
        // List all registered post-processors
        let result = try Xberg.listPostProcessors()
    }

}
