// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:38239aba5298b05bb7627da7dd29f61167e18c420fcb64676bf355b0040d0a32
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// swift-format-ignore-file

import XCTest
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif
import Xberg
import RustBridge

/// E2e tests for category: renderer_management.
final class RendererManagementTests: XCTestCase {
    override class func setUp() {
        super.setUp()
        let _existing = ProcessInfo.processInfo.environment["SUT_URL"]
    }

    func testRenderersClear() throws {
        // Clear all renderers and verify list is empty
        let result = try Xberg.clearRenderers()
    }

    func testRenderersList() throws {
        // List all registered renderers
        let result = try Xberg.listRenderers()
    }

}
