// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c39dc9eda1096e5908f5d3623329d139e738e2f60f478cd21a1d3d23c7132388
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import io.xberg.Xberg
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module
import com.fasterxml.jackson.module.kotlin.registerKotlinModule
import io.xberg.ExtractionConfig
import io.xberg.ExtractInput

/** E2e tests for category: batch. */
class BatchTest {

    companion object {
        init {
            try {
                System.loadLibrary("xberg_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load xberg_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
        private val MAPPER = ObjectMapper().registerModule(Jdk8Module()).registerKotlinModule().setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
    }
    @Test
    fun testBatchBytesInvalidMime() = runBlocking {
        // batch_extract_bytes_sync invalid MIME
        val input = MAPPER.readValue("{\"items\":[{\"content\":[72,101,108,108,111],\"mime_type\":\"application/x-nonexistent\"}]}", ExtractionConfig::class.java)
        val result = Xberg.extract(input, ExtractionConfig())
    }

    @Test
    fun testBatchExtractBytesHappy() = runBlocking {
        // batch_extract_bytes: happy path with mixed inputs
        val input = MAPPER.readValue("{\"items\":[{\"content\":[72,101,108,108,111,44,32,119,111,114,108,100,33],\"mime_type\":\"text/plain\"},{\"content\":[60,104,116,109,108,62,60,98,111,100,121,62,84,101,115,116,60,47,98,111,100,121,62,60,47,104,116,109,108,62],\"mime_type\":\"text/html\"}]}", ExtractionConfig::class.java)
        val result = Xberg.extract(input, ExtractionConfig())
        assertTrue(result.size >= 1, "expected at least 1 elements")
    }

    @Test
    fun testBatchExtractBytesMixedFormat() = runBlocking {
        // batch_extract_bytes: handles unsupported MIME gracefully
        val input = MAPPER.readValue("{\"items\":[{\"content\":[80,68,70,32,112,108,97,99,101,104,111,108,100,101,114],\"mime_type\":\"application/x-unknown\"}]}", ExtractionConfig::class.java)
        val result = Xberg.extract(input, ExtractionConfig())
    }

    @Test
    fun testBatchExtractBytesSyncEmptyList() = runBlocking {
        // batch_extract_bytes_sync: empty batch
        val input = MAPPER.readValue("{\"items\":[]}", ExtractionConfig::class.java)
        val result = Xberg.extract(input, ExtractionConfig())
        assertEquals(0, result.size, "expected exactly 0 elements")
    }

    @Test
    fun testBatchExtractBytesSyncInvalidMime() = runBlocking {
        // batch_extract_bytes_sync: unsupported MIME
        val input = MAPPER.readValue("{\"items\":[{\"content\":[100,97,116,97],\"mime_type\":\"application/x-unknown\"}]}", ExtractionConfig::class.java)
        val result = Xberg.extract(input, ExtractionConfig())
    }

    @Test
    fun testBatchFileAsyncBasic() = runBlocking {
        // Extract text from multiple files asynchronously
        val input = MAPPER.readValue("{\"paths\":[{\"path\":\"pdf/fake_memo.pdf\"},{\"path\":\"text/fake_text.txt\"}]}", ExtractionConfig::class.java)
        val result = Xberg.extract(input, ExtractionConfig())
    }

    @Test
    fun testBatchFileAsyncNotFound() = runBlocking {
        // batch_extract_file async nonexistent
        val input = MAPPER.readValue("{\"paths\":[{\"path\":\"/nonexistent/a.pdf\"}]}", ExtractionConfig::class.java)
        val result = Xberg.extract(input, ExtractionConfig())
    }

    @Test
    fun testBatchFileNotFound() = runBlocking {
        // batch_extract_file_sync nonexistent
        val input = MAPPER.readValue("{\"paths\":[{\"path\":\"/nonexistent/a.pdf\"},{\"path\":\"/nonexistent/b.txt\"}]}", ExtractionConfig::class.java)
        val result = Xberg.extract(input, ExtractionConfig())
    }

    @Test
    fun testBatchFilePartial() = runBlocking {
        // batch_extract_file_sync mixed
        val input = MAPPER.readValue("{\"paths\":[{\"path\":\"text/plain.txt\"},{\"path\":\"/nonexistent/missing.pdf\"}]}", ExtractionConfig::class.java)
        val result = Xberg.extract(input, ExtractionConfig())
    }

    @Test
    fun testBatchFileSyncBasic() = runBlocking {
        // Extract text from multiple files synchronously
        val input = MAPPER.readValue("{\"paths\":[{\"path\":\"pdf/fake_memo.pdf\"},{\"path\":\"text/fake_text.txt\"}]}", ExtractionConfig::class.java)
        val result = Xberg.extract(input, ExtractionConfig())
    }

}
