// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c39dc9eda1096e5908f5d3623329d139e738e2f60f478cd21a1d3d23c7132388
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import io.xberg.Xberg
import io.xberg.EmbeddingBackendBridge
import io.xberg.IEmbeddingBackend
import io.xberg.*

/** E2e tests for category: embedding_backend_management. */
class EmbeddingBackendManagementTest {

    companion object {
        init {
            try {
                System.loadLibrary("xberg_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load xberg_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
    }
    @Test
    fun testEmbeddingBackendsClear() = runBlocking {
        // Clear all embedding backends and verify list is empty
        val result = EmbeddingBackendBridge.clearAll()
    }

    @Test
    fun testEmbeddingBackendsList() = runBlocking {
        // List all registered embedding backends
        val result = Xberg.listEmbeddingBackends()
    }

}
