// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:33cd355feac899a31cf1fb6f8a5313ff322dad245ad8c30d97279d07b63f4a51
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import io.xberg.Xberg
import io.xberg.PostProcessorBridge
import io.xberg.IPostProcessor
import io.xberg.*

/** E2e tests for category: post_processor_management. */
class PostProcessorManagementTest {

    companion object {
        init {
            // Suite-level environment defaults from [e2e.env]. JVM OS env is
            // immutable; System.setProperty is the runtime-mutable analog. Each
            // entry uses setdefault semantics: only applied when not already set.
            if (System.getProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK") == null) {
                System.setProperty("CRAWLBERG_ALLOW_PRIVATE_NETWORK", "true")
            }
            try {
                System.loadLibrary("xberg_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load xberg_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
    }
    @Test
    fun testPostProcessorsClear() = runBlocking {
        // Clear all post-processors and verify list is empty
        val result = PostProcessorBridge.clearAll()
    }

    @Test
    fun testPostProcessorsList() = runBlocking {
        // List all registered post-processors
        val result = Xberg.listPostProcessors()
    }

}
