// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:38239aba5298b05bb7627da7dd29f61167e18c420fcb64676bf355b0040d0a32
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg.e2e

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.assertFalse
import kotlin.test.assertFailsWith
import kotlinx.coroutines.runBlocking
import io.xberg.Xberg
import io.xberg.PostProcessorBridge
import io.xberg.IPostProcessor
import io.xberg.*

/** E2e tests for category: post_processor_management. */
class PostProcessorManagementTest {

    companion object {
        init {
            try {
                System.loadLibrary("xberg_jni")
            } catch (e: UnsatisfiedLinkError) {
                System.err.println("Failed to load xberg_jni library: ${e.message}")
                val libPath = System.getProperty("java.library.path")
                System.err.println("java.library.path: $libPath")
                throw e
            }
        }
    }
    @Test
    fun testPostProcessorsClear() = runBlocking {
        // Clear all post-processors and verify list is empty
        val result = PostProcessorBridge.clearAll()
    }

    @Test
    fun testPostProcessorsList() = runBlocking {
        // List all registered post-processors
        val result = Xberg.listPostProcessors()
    }

}
