/**
 * Generated by alef. Do not edit by hand.
 * alef:hash:c26185e7af68ca4756f10e088470f87071eb21785e05d75acd73c4ee0d7abef9
 *
 * TypeScript trait bridge for outbound plugin implementations.
 */

export interface EmbeddingBackendBridge {
  name(): string;
  version(): string;
  initialize(): Promise<void>;
  shutdown(): Promise<void>;
  dimensions(): string;
  embed?(texts: string): string;
}

export class EmbeddingBackendAdapter {
  constructor(private bridge: EmbeddingBackendBridge) {}

  async dimensions(): Promise<string> {
    try {
      const result = await this.bridge.dimensions();
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

  async embed(texts: string): Promise<string> {
    try {
      const result = await this.bridge.embed(texts);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

}
