/**
 * Generated by alef. Do not edit by hand.
 * alef:hash:4c69455352c6694c6639030ae0ef9d405ca032b08d85d13bed84086fcdf60c8d
 *
 * TypeScript trait bridge for outbound plugin implementations.
 */

export interface RerankerBackendBridge {
  name(): string;
  version(): string;
  initialize(): Promise<void>;
  shutdown(): Promise<void>;
  rerank?(query: string, documents: string): string;
}

export class RerankerBackendAdapter {
  constructor(private bridge: RerankerBackendBridge) {}

  async rerank(query: string, documents: string): Promise<string> {
    try {
      const result = await this.bridge.rerank(query, documents);
      return JSON.stringify({ ok: result });
    } catch (e) {
      return JSON.stringify({ err: String(e) });
    }
  }

}
