# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c77367def0c186dd0b48cb2b2bf3ff806a3fbb1ed6f53e58e23be8070ca92581
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: detection

test_that("detect_mime_bytes_html: Detect HTML MIME from bytes", {
  result <- detect_mime_type_from_bytes(content = readBin(.resolve_fixture("html/html.html"), what = "raw", n = file.info(.resolve_fixture("html/html.html"))$size))
  expect_true(TRUE)
})

test_that("detect_mime_bytes_pdf: Detect PDF MIME type from bytes", {
  result <- detect_mime_type_from_bytes(content = readBin(.resolve_fixture("pdf/fake_memo.pdf"), what = "raw", n = file.info(.resolve_fixture("pdf/fake_memo.pdf"))$size))
  expect_true(TRUE)
})

test_that("detect_mime_bytes_png: Detect PNG MIME type from bytes", {
  result <- detect_mime_type_from_bytes(content = readBin(.resolve_fixture("images/test_hello_world.png"), what = "raw", n = file.info(.resolve_fixture("images/test_hello_world.png"))$size))
  expect_true(TRUE)
})

test_that("get_extensions_unknown_mime: get_extensions unknown MIME", {
  expect_error(get_extensions_for_mime(mime_type = "application/x-totally-unknown"))
})
