# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7bb47b3eb8fa7d05becbd48b492cfc1c38de1d745c438352b85f7a7d0f913ab4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: registry_operations

test_that("extensions_docx: Get file extensions for DOCX MIME type", {
  result <- get_extensions_for_mime(mime_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
})

test_that("extensions_html: Get file extensions for HTML MIME type", {
  result <- get_extensions_for_mime(mime_type = "text/html")
})

test_that("extensions_pdf: Get file extensions for PDF MIME type", {
  result <- get_extensions_for_mime(mime_type = "application/pdf")
  expect_true(grepl("pdf", result, fixed = TRUE))
})
