# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ed3cb40867508fa3eec90029cd9b152fdf7e4e73fee5fbfc634f8ffc8b09db01
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
# E2e tests for category: embedding_backend_management

test_that("embedding_backends_clear: Clear all embedding backends and verify list is empty", {
  invisible(clear_embedding_backends())
  expect_true(TRUE)
})

test_that("embedding_backends_list: List all registered embedding backends", {
  result <- list_embedding_backends()
  expect_true(TRUE)
})
