// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d63e0283476bd8f41fd1b07ab7d0bbfde196679db404e32bcf4edb1a021f1f52
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A cache read or write operation failed.
/// </summary>
public class CacheException : XbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
