// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a8a2fb5049e2e094c83b3ad2e0f6f13f62b4fea58f71c4a4f1e331a37b4cdec3
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The extraction was cancelled via a `CancellationToken`.
/// </summary>
public class CancelledException : XbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
