// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7d69f93c62f49996446ca8e109bc69aee242e943de2dc761a797a89f85d56f7c
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file validates but cannot be deserialized into `Preset`.
/// </summary>
public class DeserializeException : LoadErrorException
{
    public DeserializeException(string message) : base(message) { }

    public DeserializeException(string message, Exception innerException) : base(message, innerException) { }
}
