// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:eb5be1c33cb28fe9cd7339926a1508239529d634524a0fcd5f530dcb435666df
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The embedding model or embedding pipeline returned an error.
/// </summary>
public class EmbeddingException : XbergErrorException
{
    public EmbeddingException(string message) : base(message) { }

    public EmbeddingException(string message, Exception innerException) : base(message, innerException) { }
}
