// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:93495e965e210d9c9496568d953da9966b0458b005882a1322aabdf15b34ce0c
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The embedding model or embedding pipeline returned an error.
/// </summary>
public class EmbeddingException : XbergErrorException
{
    public EmbeddingException(string message) : base(message) { }

    public EmbeddingException(string message, Exception innerException) : base(message, innerException) { }
}
