// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7b6093f244759948a70f40a504f7baff35f202ad22a2e3925f5b4946344cde9b
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The preset's declared `id` does not match its file-system location.
/// </summary>
public class IdMismatchException : LoadErrorException
{
    public IdMismatchException(string message) : base(message) { }

    public IdMismatchException(string message, Exception innerException) : base(message, innerException) { }
}
