// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c39dc9eda1096e5908f5d3623329d139e738e2f60f478cd21a1d3d23c7132388
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Document parsing failed (e.g. corrupt file, unsupported format feature).
/// </summary>
public class ParsingException : XbergErrorException
{
    public ParsingException(string message) : base(message) { }

    public ParsingException(string message, Exception innerException) : base(message, innerException) { }
}
