// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:49d7737c4c8395f019e87ea16ab3317aeda42281d98fd36f5ee4369a81b3e523
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A registered plugin returned an error during extraction.
/// </summary>
public class PluginException : XbergErrorException
{
    public PluginException(string message) : base(message) { }

    public PluginException(string message, Exception innerException) : base(message, innerException) { }
}
