// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:eb5be1c33cb28fe9cd7339926a1508239529d634524a0fcd5f530dcb435666df
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The reranker model or reranking pipeline returned an error.
///
/// Since v5.0.0.
/// </summary>
public class RerankingException : XbergErrorException
{
    public RerankingException(string message) : base(message) { }

    public RerankingException(string message, Exception innerException) : base(message, innerException) { }
}
