// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:33cd355feac899a31cf1fb6f8a5313ff322dad245ad8c30d97279d07b63f4a51
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors produced while resolving a preset against caller overrides.
/// </summary>
public class ResolveErrorException : XbergException
{
    public ResolveErrorException(string message) : base(message) { }

    public ResolveErrorException(string message, Exception innerException) : base(message, innerException) { }
}
