// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:52d810dddba1010b606994310ce2a05f1937641c736814d217688096779f4320
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Errors produced while resolving a preset against caller overrides.
/// </summary>
public class ResolveErrorException : XbergException
{
    public ResolveErrorException(string message) : base(message) { }

    public ResolveErrorException(string message, Exception innerException) : base(message, innerException) { }
}
