// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:926a121ce8858da89e1c2dae78836bd02775ed955b144da6ce043a83737b8c26
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A custom schema override was supplied but is not a JSON object.
/// </summary>
public class SchemaNotObjectException : ResolveErrorException
{
    public SchemaNotObjectException(string message) : base(message) { }

    public SchemaNotObjectException(string message, Exception innerException) : base(message, innerException) { }
}
