// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:38239aba5298b05bb7627da7dd29f61167e18c420fcb64676bf355b0040d0a32
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// The file parses as JSON but does not validate against the meta-schema.
/// </summary>
public class SchemaValidationException : LoadErrorException
{
    public SchemaValidationException(string message) : base(message) { }

    public SchemaValidationException(string message, Exception innerException) : base(message, innerException) { }
}
