// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:eb5be1c33cb28fe9cd7339926a1508239529d634524a0fcd5f530dcb435666df
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// A security policy was violated (e.g. zip bomb, oversized archive).
/// </summary>
public class SecurityException : XbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
