// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:eb5be1c33cb28fe9cd7339926a1508239529d634524a0fcd5f530dcb435666df
#nullable enable

using System;

namespace Xberg;

/// <summary>
/// Audio/video transcription failed.
/// </summary>
public class TranscriptionException : XbergErrorException
{
    public TranscriptionException(string message) : base(message) { }

    public TranscriptionException(string message, Exception innerException) : base(message, innerException) { }
}
