// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c39dc9eda1096e5908f5d3623329d139e738e2f60f478cd21a1d3d23c7132388
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
const std = @import("std");
const testing = std.testing;
const xberg = @import("xberg");

// Suppress C++ global destructor aborts that break zig's --listen=- IPC
extern "c" fn signal(sig: i32, handler: usize) usize;
var _abort_handler_installed: bool = false;
fn suppress_abort() void {
    if (!_abort_handler_installed) {
        // SIGABRT = 6 on POSIX; SIG_IGN = 1
        _ = signal(6, 1);
        _abort_handler_installed = true;
    }
}

// E2e tests for category: batch

test "batch_bytes_invalid_mime" {
    // batch_extract_bytes_sync invalid MIME
    suppress_abort();
    const _result_json = try xberg.extract("{\"items\":[{\"content\":[72,101,108,108,111],\"mime_type\":\"application/x-nonexistent\"}]}", "{}");
    defer std.heap.c_allocator.free(_result_json);
}

test "batch_extract_bytes_happy" {
    // batch_extract_bytes: happy path with mixed inputs
    suppress_abort();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try xberg.extract("{\"items\":[{\"content\":[72,101,108,108,111,44,32,119,111,114,108,100,33],\"mime_type\":\"text/plain\"},{\"content\":[60,104,116,109,108,62,60,98,111,100,121,62,84,101,115,116,60,47,98,111,100,121,62,60,47,104,116,109,108,62],\"mime_type\":\"text/html\"}]}", "{}");
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expect(result.array.items.len >= @as(usize, 1));
}

test "batch_extract_bytes_mixed_format" {
    // batch_extract_bytes: handles unsupported MIME gracefully
    suppress_abort();
    const _result_json = try xberg.extract("{\"items\":[{\"content\":[80,68,70,32,112,108,97,99,101,104,111,108,100,101,114],\"mime_type\":\"application/x-unknown\"}]}", "{}");
    defer std.heap.c_allocator.free(_result_json);
}

test "batch_extract_bytes_sync_empty_list" {
    // batch_extract_bytes_sync: empty batch
    suppress_abort();
    var gpa: std.heap.DebugAllocator(.{}) = .init;
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    const _result_json = try xberg.extract("{\"items\":[]}", "{}");
    defer std.heap.c_allocator.free(_result_json);
    var _parsed = try std.json.parseFromSlice(std.json.Value, allocator, _result_json, .{});
    defer _parsed.deinit();
    const result = &_parsed.value;
    try testing.expectEqual(@as(usize, 0), result.array.items.len);
}

test "batch_extract_bytes_sync_invalid_mime" {
    // batch_extract_bytes_sync: unsupported MIME
    suppress_abort();
    const _result_json = try xberg.extract("{\"items\":[{\"content\":[100,97,116,97],\"mime_type\":\"application/x-unknown\"}]}", "{}");
    defer std.heap.c_allocator.free(_result_json);
}

test "batch_file_async_basic" {
    // Extract text from multiple files asynchronously
    suppress_abort();
    const _result_json = try xberg.extract("{\"paths\":[{\"path\":\"pdf/fake_memo.pdf\"},{\"path\":\"text/fake_text.txt\"}]}", "{}");
    defer std.heap.c_allocator.free(_result_json);
}

test "batch_file_async_not_found" {
    // batch_extract_file async nonexistent
    suppress_abort();
    const _result_json = try xberg.extract("{\"paths\":[{\"path\":\"/nonexistent/a.pdf\"}]}", "{}");
    defer std.heap.c_allocator.free(_result_json);
}

test "batch_file_not_found" {
    // batch_extract_file_sync nonexistent
    suppress_abort();
    const _result_json = try xberg.extract("{\"paths\":[{\"path\":\"/nonexistent/a.pdf\"},{\"path\":\"/nonexistent/b.txt\"}]}", "{}");
    defer std.heap.c_allocator.free(_result_json);
}

test "batch_file_partial" {
    // batch_extract_file_sync mixed
    suppress_abort();
    const _result_json = try xberg.extract("{\"paths\":[{\"path\":\"text/plain.txt\"},{\"path\":\"/nonexistent/missing.pdf\"}]}", "{}");
    defer std.heap.c_allocator.free(_result_json);
}

test "batch_file_sync_basic" {
    // Extract text from multiple files synchronously
    suppress_abort();
    const _result_json = try xberg.extract("{\"paths\":[{\"path\":\"pdf/fake_memo.pdf\"},{\"path\":\"text/fake_text.txt\"}]}", "{}");
    defer std.heap.c_allocator.free(_result_json);
}
