<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:eb5be1c33cb28fe9cd7339926a1508239529d634524a0fcd5f530dcb435666df
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Xberg;

/**
 * Compiled meta-schema validator over `preset.schema.json`.
 */
final class MetaSchema
{
    /**
     * Validate `raw` against the meta-schema and deserialize into a `Preset`,
     */
    public function parsePreset(string $path, string $raw): Preset
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * Compile the given JSON text as a Draft 2020-12 meta-schema.
     */
    public static function compile(string $meta_schema_json): MetaSchema
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
