<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e4a17520766145e761ea1662da07f7497a7f2fd19fcf9ecada67bc4a6ab85861
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
declare(strict_types=1);

namespace Kreuzberg;

/**
 * Per-category running counter for `RedactionStrategy.TokenReplace`.
 */
final class TokenCounter
{
    /**
     * Allocate the next token for `category` and `original`. If the original
     */
    public function nextToken(PiiCategory $category, string $original): string
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    public static function new(): TokenCounter
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
