<?php

// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6e273900ce19c7622b0762a1859860b5d4a3fd0209372543c5555415f48cc0a2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
declare(strict_types=1);

namespace Kreuzberg;

/**
 * Per-category running counter for `RedactionStrategy.TokenReplace`.
 */
final class TokenCounter
{
    /**
     * Create a fresh counter with no previous state.
     */
    public static function new(): TokenCounter
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
