// Generated by alef. Do not edit by hand.
// alef:hash:76dabbbc48f44358b4e72324b0f3fb0ea5555b0846c36bab986b34e87c098baf
// swift-format-ignore-file
// This file contains the base protocol that all trait bridges inherit from.

import Foundation

/// Base protocol that all trait bridges must conform to.
/// Declares the four Plugin trait super-methods for lifecycle management.
public protocol SwiftPluginBridge: AnyObject {
    /// Returns the unique name/identifier for this plugin.
    var name: String { get }

    /// Returns the semantic version of this plugin.
    func version() -> String

    /// Initialize the plugin.
    func initialize() throws

    /// Shutdown the plugin.
    func shutdown() throws
}
