// Generated by alef. Do not edit by hand.
// alef:hash:a8a2fb5049e2e094c83b3ad2e0f6f13f62b4fea58f71c4a4f1e331a37b4cdec3
// swift-format-ignore-file
// This file contains the base protocol that all trait bridges inherit from.

import Foundation

/// Base protocol that all trait bridges must conform to.
/// Declares the four Plugin trait super-methods for lifecycle management.
public protocol SwiftPluginBridge: AnyObject {
  /// Returns the unique name/identifier for this plugin.
  var name: String { get }

  /// Returns the semantic version of this plugin.
  func version() -> String

  /// Initialize the plugin.
  func initialize() throws

  /// Shutdown the plugin.
  func shutdown() throws
}
