// Generated by alef. Do not edit by hand.
// alef:hash:fa49f061b4922ae545a884b3557c72331bc9acf91f2b03d4dfc68363dc9f62b9
// swift-format-ignore-file
// This file contains generated FFI glue for plugin Box classes.

import Foundation
import RustBridge

/// Opaque box class retained by Rust via `Unmanaged<SwiftRendererBox>.passRetained`.
/// Wraps `any SwiftRendererBridge` and exposes `alef_*` FFI shim methods.
/// swift-bridge @_cdecl shims call these methods directly.
public final class SwiftRendererBox {
    private let bridge: any SwiftRendererBridge
    public init(_ bridge: any SwiftRendererBridge) { self.bridge = bridge }
    // MARK: Plugin super-trait shims

    public func alef_name() -> RustString {
        return RustString(bridge.name)
    }

    public func alef_version() -> RustString {
        return RustString(bridge.version())
    }

    public func alef_initialize() -> String {
        do {
            try bridge.initialize()
            return encodeOkVoidEnvelope()
        } catch { return encodeErrEnvelope("\(error)") }
    }

    public func alef_shutdown() -> String {
        do {
            try bridge.shutdown()
            return encodeOkVoidEnvelope()
        } catch { return encodeErrEnvelope("\(error)") }
    }

    // MARK: Trait-specific shims
    public func alef_render(doc: RustString) -> String {
        do {
          let result = try bridge.render(doc: doc.toString())
          return encodeOkEnvelope(result)
        } catch { return encodeErrEnvelope("\(error)") }
    }
}
