// Generated by alef. Do not edit by hand.
// alef:hash:fa49f061b4922ae545a884b3557c72331bc9acf91f2b03d4dfc68363dc9f62b9
// swift-format-ignore-file
// This file contains generated FFI glue for plugin Box classes.

import Foundation
import RustBridge

/// Opaque box class retained by Rust via `Unmanaged<SwiftValidatorBox>.passRetained`.
/// Wraps `any SwiftValidatorBridge` and exposes `alef_*` FFI shim methods.
/// swift-bridge @_cdecl shims call these methods directly.
public final class SwiftValidatorBox {
    private let bridge: any SwiftValidatorBridge
    public init(_ bridge: any SwiftValidatorBridge) { self.bridge = bridge }
    // MARK: Plugin super-trait shims

    public func alef_name() -> RustString {
        return RustString(bridge.name)
    }

    public func alef_version() -> RustString {
        return RustString(bridge.version())
    }

    public func alef_initialize() -> String {
        do {
            try bridge.initialize()
            return encodeOkVoidEnvelope()
        } catch { return encodeErrEnvelope("\(error)") }
    }

    public func alef_shutdown() -> String {
        do {
            try bridge.shutdown()
            return encodeOkVoidEnvelope()
        } catch { return encodeErrEnvelope("\(error)") }
    }

    // MARK: Trait-specific shims
    public func alef_validate(result: RustString, config: RustString) -> String {
        do {
          try bridge.validate(result: result.toString(), config: config.toString())
          return encodeOkVoidEnvelope()
        } catch { return encodeErrEnvelope("\(error)") }
    }
    public func alef_should_validate(result: RustString, config: RustString) -> Bool {
        return bridge.shouldValidate(result: result.toString(), config: config.toString())
    }
    public func alef_priority() -> Int32 {
        return bridge.priority()
    }
}
