# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:287fad381b3957c7a43d86285d13b15d426626ead595e8992131a4cf4fbe6bda
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef

"""E2e tests for category: ocr_backend_management."""

import pytest  # noqa: F401
from kreuzberg import clear_ocr_backends, list_ocr_backends, unregister_ocr_backend


def _alef_e2e_text(value: object) -> str:
    return "" if value is None else str(value)


def _alef_e2e_item_texts(item: object) -> tuple[str, ...]:
    raw_items = getattr(item, "items", None)
    items_text = " ".join(str(value) for value in raw_items) if isinstance(raw_items, list) else ""
    return (
        _alef_e2e_text(item),
        _alef_e2e_text(getattr(item, "kind", None)),
        _alef_e2e_text(getattr(item, "name", None)),
        _alef_e2e_text(getattr(item, "source", None)),
        _alef_e2e_text(getattr(item, "alias", None)),
        _alef_e2e_text(getattr(item, "text", None)),
        _alef_e2e_text(getattr(item, "signature", None)),
        items_text,
    )


def test_ocr_backends_clear() -> None:
    """Clear all OCR backends and verify list is empty."""
    _ = clear_ocr_backends()


def test_ocr_backends_list() -> None:
    """List all registered OCR backends."""
    _ = list_ocr_backends()


def test_ocr_backends_unregister() -> None:
    """Unregister nonexistent OCR backend gracefully."""
    name = "nonexistent-backend-xyz"

    _ = unregister_ocr_backend(name)
