// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:fa49f061b4922ae545a884b3557c72331bc9acf91f2b03d4dfc68363dc9f62b9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: document_extractor_management. */
public class DocumentExtractorManagementTest {

    @Test
    void testDocumentExtractorsClear() throws Exception {
        // Clear all document extractors and verify list is empty
        Kreuzberg.clearDocumentExtractors();


    }


    @Test
    void testExtractorsList() throws Exception {
        // List all registered document extractors
        var result = Kreuzberg.listDocumentExtractors();


    }

}
