// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:eec9c44b3a7cfcd5d9fd49a2197aa3b818d444a55cc68863b6c69bad344326b9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

package dev.kreuzberg.e2e;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import dev.kreuzberg.Kreuzberg;
import dev.kreuzberg.ExtractionConfig;
import java.util.Optional;
import dev.kreuzberg.JsonUtil;

/** E2e tests for category: registry_operations. */
public class RegistryOperationsTest {

    @Test
    void testExtensionsDocx() throws Exception {
        // Get file extensions for DOCX MIME type
        var result = Kreuzberg.getExtensionsForMime("application/vnd.openxmlformats-officedocument.wordprocessingml.document");


    }


    @Test
    void testExtensionsHtml() throws Exception {
        // Get file extensions for HTML MIME type
        var result = Kreuzberg.getExtensionsForMime("text/html");


    }


    @Test
    void testExtensionsPdf() throws Exception {
        // Get file extensions for PDF MIME type
        var result = Kreuzberg.getExtensionsForMime("application/pdf");


    }

}
