# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:287fad381b3957c7a43d86285d13b15d426626ead595e8992131a4cf4fbe6bda
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
library(testthat)
devtools::load_all("../../packages/r")

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
