# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f4f642e9fabe0d17f1b24f177219b39c0511f431e4e3ed1a52330a0e0fe5e3bf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require 'json'
require 'kreuzberg_rb'
