# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:faba9bd9cd6459916b35befc0016d7e4c4a5fff356d7aa478c51dd1ac966f022
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module Kreuzberg
  ## The version string for this package.
  VERSION = "5.0.0.pre.rc.10"
end
