# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eec9c44b3a7cfcd5d9fd49a2197aa3b818d444a55cc68863b6c69bad344326b9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

module Kreuzberg
  VERSION = "5.0.0.pre.rc.3"
end
