// DO NOT EDIT - auto-generated by alef
// alef:hash:eec9c44b3a7cfcd5d9fd49a2197aa3b818d444a55cc68863b6c69bad344326b9
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
