// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0336260e302c26ff585c4c04aceb3a97bacbca7a5eb642e1813c88dd18ea364d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
package dev.kreuzberg;

import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Image metadata extracted from an image file.
 */
public record ExtractedImageMetadata(
    /**
     * Image width in pixels
     */
    int width,
    /**
     * Image height in pixels
     */
    int height,
    /**
     * Image format (e.g., "PNG", "JPEG")
     */
    String format,
    /**
     * EXIF data if available
     */
    @JsonProperty("exif_data") Map<String, String> exifData
) {
}
