// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0336260e302c26ff585c4c04aceb3a97bacbca7a5eb642e1813c88dd18ea364d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public enum FracType {
    Bar("bar"),
    NoBar("nobar"),
    Linear("linear"),
    Skewed("skewed");

    /** The string value. */
    private final String value;

    FracType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static FracType fromValue(final String value) {
        for (FracType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
