// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c77367def0c186dd0b48cb2b2bf3ff806a3fbb1ed6f53e58e23be8070ca92581
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * kreuzberg-gliner-rs ONNX backend wrapper.
 *
 * Holds an initialised GLiNER&lt;SpanMode&gt; behind an {@code Arc&lt;Mutex&lt;...&gt;&gt;} so the
 * model can be safely shared across async tasks (inference is synchronous and
 * serialised internally by the mutex).
 */
public record GlineBackend(
    @JsonProperty("repo_id") String repoId,
    @JsonProperty("model_path") java.nio.file.Path modelPath,
    @JsonProperty("tokenizer_path") java.nio.file.Path tokenizerPath
) {
    /**
     * Build a backend for {@code repo_id} (or the default model if {@code None}).
     *
     * Downloads the ONNX weights and tokenizer via {@code hf-hub} on first call.
     * After this returns, inference is available without further I/O.
     */
    public static GlineBackend create(String repoId) {
        throw new UnsupportedOperationException("create is not yet bridged via JNI; use the Builder instead.");
    }
}
