// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1e76f851164182cee6be39ea7bd537fe5e636e056f07b1ac9047683168c541a2
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Heading context for a chunk within a Markdown document.
 *
 * Contains the heading hierarchy from document root to this chunk's section.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = HeadingContext.Builder.class)
@SuppressWarnings("PMD")
public record HeadingContext(@JsonProperty("headings") List<HeadingLevel> headings) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

private List<HeadingLevel> headings = List.of();

        /** Sets the headings field. */
        @JsonProperty("headings")
        public Builder withHeadings(final List<HeadingLevel> value) {
            this.headings = value;
            return this;
        }

        /** Builds the HeadingContext instance. */
        public HeadingContext build() {
            return new HeadingContext(
                headings
            );
        }
    }
    // CPD-ON
}
