// DO NOT EDIT - auto-generated by alef
// alef:hash:faba9bd9cd6459916b35befc0016d7e4c4a5fff356d7aa478c51dd1ac966f022
package dev.kreuzberg;

/**
 * A required optional system dependency (e.g. `tesseract`) was not found.
 */
public class MissingDependencyException extends KreuzbergErrorException {
    /** Creates a new MissingDependencyException with the given message. */
    public MissingDependencyException(final String message) {
        super(message);
    }

    /** Creates a new MissingDependencyException with the given message and cause. */
    public MissingDependencyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
