// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e4a17520766145e761ea1662da07f7497a7f2fd19fcf9ecada67bc4a6ab85861
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

/**
 * Bounding geometry for an OCR element.
 *
 * Supports both axis-aligned rectangles (from Tesseract) and 4-point quadrilaterals
 * (from PaddleOCR and rotated text detection).
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "type", visible = false)
@JsonSubTypes({
    @JsonSubTypes.Type(value = OcrBoundingGeometry.Rectangle.class, name = "rectangle"),
    @JsonSubTypes.Type(value = OcrBoundingGeometry.Quadrilateral.class, name = "quadrilateral")
})
@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)
public sealed interface OcrBoundingGeometry {

    /**
     * Axis-aligned bounding box (typical for Tesseract output).
     */
    record Rectangle(
        @JsonProperty("left") int left,
        @JsonProperty("top") int top,
        @JsonProperty("width") int width,
        @JsonProperty("height") int height
    ) implements OcrBoundingGeometry {
    }

    /**
     * 4-point quadrilateral for rotated/skewed text (PaddleOCR).
     *
     * Points are in clockwise order starting from top-left:
     * {@code [top_left, top_right, bottom_right, bottom_left]}
     */
    record Quadrilateral(@JsonProperty("points") String points) implements OcrBoundingGeometry { }
}
