// DO NOT EDIT - auto-generated by alef
// alef:hash:0336260e302c26ff585c4c04aceb3a97bacbca7a5eb642e1813c88dd18ea364d
package dev.kreuzberg;

public class OtherException extends KreuzbergErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
