// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:0336260e302c26ff585c4c04aceb3a97bacbca7a5eb642e1813c88dd18ea364d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/sample_crate-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Outlook PST archive metadata.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PstMetadata.Builder.class)
public record PstMetadata(@JsonProperty("message_count") long messageCount) {
    public static Builder builder() {
        return new Builder();
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("message_count")
private long messageCount = 0;

        /** Sets the messageCount field. */
        @JsonProperty("message_count")
        public Builder withMessageCount(final long value) {
            this.messageCount = value;
            return this;
        }

        /** Builds the PstMetadata instance. */
        public PstMetadata build() {
            return new PstMetadata(
                messageCount
            );
        }
    }
    // CPD-ON
}
