// DO NOT EDIT - auto-generated by alef
// alef:hash:fa49f061b4922ae545a884b3557c72331bc9acf91f2b03d4dfc68363dc9f62b9
package dev.kreuzberg;

/**
 * Errors produced while resolving a preset against caller overrides.
 */
public class ResolveErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new ResolveErrorException with the given message. */
  public ResolveErrorException(final String message) {
    super(message);
  }

  /** Creates a new ResolveErrorException with the given message and cause. */
  public ResolveErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
