// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:faba9bd9cd6459916b35befc0016d7e4c4a5fff356d7aa478c51dd1ac966f022
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Text direction enumeration for HTML documents.
 */
@SuppressWarnings("PMD")
public enum TextDirection {
    /**
     * Left-to-right text direction
     */
    LeftToRight("ltr"),
    /**
     * Right-to-left text direction
     */
    RightToLeft("rtl"),
    /**
     * Automatic text direction detection
     */
    Auto("auto");


    /** The string value. */
    private final String value;

    TextDirection(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static TextDirection fromValue(final String value) {
        for (TextDirection e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown TextDirection value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
