// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5f6a515f4cee741e840244242f9d162610a0d8a3fcdf086410779e59b2395d39
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * Per-category running counter for RedactionStrategy.TokenReplace.
 */
@SuppressWarnings("PMD")
public class TokenCounter implements AutoCloseable {
    private final MemorySegment handle;

    TokenCounter(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }
    /**
     * Create a fresh counter with no previous state.
     */
    public static TokenCounter create() throws KreuzbergRsException {
        try {
            var handle = (MemorySegment) NativeLib.KREUZBERG_TOKEN_COUNTER_NEW.invoke();
            if (handle == null || handle.equals(MemorySegment.NULL)) {
                throw new KreuzbergRsException("create returned null", (Throwable) null);
            }
            return new TokenCounter(handle);
        }
        catch (Throwable e) {
            if (e instanceof KreuzbergRsException) throw (KreuzbergRsException) e;
            throw new RuntimeException("create failed: " + e.getMessage(), e);
        }
    }
    @Override
    @SuppressWarnings("PMD.AvoidCatchingGenericException")
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_TOKEN_COUNTER_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free TokenCounter: " + e.getMessage(), e);
            }
        }
    }
}
