// DO NOT EDIT - auto-generated by alef
// alef:hash:5c2a3fd9729453c7020e8a1ed4d1ef626b5f48c2861b32bca702aef7a4b1fbe9
package dev.kreuzberg;

/**
 * Audio/video transcription failed.
 */
public class TranscriptionException extends KreuzbergErrorException {
    /** Creates a new TranscriptionException with the given message. */
    public TranscriptionException(final String message) {
        super(message);
    }

    /** Creates a new TranscriptionException with the given message and cause. */
    public TranscriptionException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
