// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c77367def0c186dd0b48cb2b2bf3ff806a3fbb1ed6f53e58e23be8070ca92581
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * YAKE-specific parameters.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = YakeParams.Builder.class)
public record YakeParams(@JsonProperty("window_size") long windowSize) {
    public static Builder builder() {
        return new Builder();
    }
    public YakeParams{
        if (windowSize == 0) windowSize = 2;
    }

    // CPD-OFF
    @JsonPOJOBuilder(withPrefix = "with", buildMethodName = "build")
    public static final class Builder {

        @JsonProperty("window_size")
private long windowSize = 0;

        /** Sets the windowSize field. */
        @JsonProperty("window_size")
        public Builder withWindowSize(final long value) {
            this.windowSize = value;
            return this;
        }

        /** Builds the YakeParams instance. */
        public YakeParams build() {
            return new YakeParams(
                windowSize
            );
        }
    }
    // CPD-ON
    public static YakeParams defaultInstance() {
        throw new UnsupportedOperationException("defaultInstance is not yet bridged via JNI; use the Builder instead.");
    }
}
