# Generated by alef. Do not edit by hand.
# alef:hash:5c2a3fd9729453c7020e8a1ed4d1ef626b5f48c2861b32bca702aef7a4b1fbe9
# Keep generated public API for consumers using R8/ProGuard.
-keep class dev.kreuzberg.** { *; }
