# Generated by alef. Do not edit by hand.
# alef:hash:faba9bd9cd6459916b35befc0016d7e4c4a5fff356d7aa478c51dd1ac966f022
# Keep generated public API for consumers using R8/ProGuard.
-keep class dev.kreuzberg.** { *; }
