# Generated by alef. Do not edit by hand.
# alef:hash:5f6a515f4cee741e840244242f9d162610a0d8a3fcdf086410779e59b2395d39
# Keep generated public API for consumers using R8/ProGuard.
-keep class dev.kreuzberg.** { *; }
