// Generated by alef. Do not edit by hand.
// alef:hash:d63e0283476bd8f41fd1b07ab7d0bbfde196679db404e32bcf4edb1a021f1f52
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/** Metadata about a document for analysis. */
data class DocumentMetadata(
    /** MIME type of the document. */
    val mimeType: String,
    /** File size in bytes. */
    val sizeBytes: Long,
    /** Page count (if known, e.g., from previous analysis). */
    val pageCount: Int? = null,
    /** Whether OCR is forced regardless of text layer. */
    val forceOcr: Boolean,
    /** User-provided chunk configuration overrides. */
    val userChunkConfig: UserChunkConfig? = null,
    /** Whether chunking is enabled for this job. */
    val chunkingEnabled: Boolean,
)
