// Generated by alef. Do not edit by hand.
// alef:hash:c39dc9eda1096e5908f5d3623329d139e738e2f60f478cd21a1d3d23c7132388

package io.xberg

object DocumentExtractorBridge {
    private val registered = mutableMapOf<String, IDocumentExtractor>()

    fun register(impl: IDocumentExtractor): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterDocumentExtractor(impl)
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterDocumentExtractor(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearDocumentExtractors()
    }

    fun getAll(): Map<String, IDocumentExtractor> = registered.toMap()
}
