// Generated by alef. Do not edit by hand.
// alef:hash:d63e0283476bd8f41fd1b07ab7d0bbfde196679db404e32bcf4edb1a021f1f52
@file:Suppress(
    "ktlint:standard:trailing-comma-on-call-site",
    "ktlint:standard:trailing-comma-on-declaration-site",
    "ktlint:standard:spacing-between-declarations-with-comments",
    "ktlint:standard:spacing-between-declarations-with-annotations",
    "ktlint:standard:when-entry-bracing",
    "ktlint:standard:blank-line-between-when-conditions",
    "ktlint:standard:blank-line-before-declaration",
    "ktlint:standard:chain-method-continuation",
    "ktlint:standard:annotation",
    "ktlint:standard:max-line-length",
    "ktlint:standard:no-semi",
    "ktlint:standard:statement-wrapping",
    "MaxLineLength",
    "TooManyFunctions",
    "FunctionParameterNaming",
    "LongParameterList",
    "CyclomaticComplexMethod",
    "LongMethod",
    "MagicNumber",
    "NestedBlockDepth",
    "ReturnCount",
    "UnusedParameter",
)

package io.xberg

/**
 * Block-level element in a Djot document.
 *
 * Represents structural elements like headings, paragraphs, lists, code blocks, etc.
 */
data class FormattedBlock(
    /** Type of block element */
    val blockType: BlockType,
    /** Heading level (1-6) for headings, or nesting level for lists */
    val level: Long? = null,
    /** Inline content within the block */
    val inlineContent: List<InlineElement> = emptyList(),
    /** Element attributes (classes, IDs, key-value pairs) */
    val attributes: String? = null,
    /** Language identifier for code blocks */
    val language: String? = null,
    /** Raw code content for code blocks */
    val code: String? = null,
    /** Nested blocks for containers (blockquotes, list items, divs) */
    val children: List<FormattedBlock> = emptyList(),
)
