// Generated by alef. Do not edit by hand.
// alef:hash:0dfdfc675fa0466d5742def18462b27194b5262bca2a05f5d7a89010cf5bb3b0

package io.xberg

object TokenizerBackendBridge {
    private val registered = mutableMapOf<String, ITokenizerBackend>()

    fun register(impl: ITokenizerBackend): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterTokenizerBackend(TokenizerBackendJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterTokenizerBackend(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearTokenizerBackends()
    }

    fun getAll(): Map<String, ITokenizerBackend> = registered.toMap()
}
