// Generated by alef. Do not edit by hand.
// alef:hash:76dabbbc48f44358b4e72324b0f3fb0ea5555b0846c36bab986b34e87c098baf

package io.xberg

object ValidatorBridge {
    private val registered = mutableMapOf<String, IValidator>()

    fun register(impl: IValidator): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterValidator(ValidatorJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterValidator(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearValidators()
    }

    fun getAll(): Map<String, IValidator> = registered.toMap()
}
