// Generated by alef. Do not edit by hand.
// alef:hash:0dfdfc675fa0466d5742def18462b27194b5262bca2a05f5d7a89010cf5bb3b0

package io.xberg

object ValidatorBridge {
    private val registered = mutableMapOf<String, IValidator>()

    fun register(impl: IValidator): Unit {
        val name = impl.name()
        registered[name] = impl
        XbergBridge.nativeRegisterValidator(ValidatorJniDispatcher(impl))
    }

    fun unregister(name: String): Unit {
        registered.remove(name)
        XbergBridge.nativeUnregisterValidator(name)
    }

    fun clearAll(): Unit {
        registered.clear()
        XbergBridge.nativeClearValidators()
    }

    fun getAll(): Map<String, IValidator> = registered.toMap()
}
