// Generated by alef. Do not edit by hand.
// alef:hash:a8a2fb5049e2e094c83b3ad2e0f6f13f62b4fea58f71c4a4f1e331a37b4cdec3

package io.xberg

/// Bridge adapter for IValidator implementations.
///
/// Wraps a user-supplied IValidator instance and delegates all method calls.
/// This adapter is used internally by the trait bridge registration layer to ensure
/// proper handling of impl instances through JNI boundaries.
internal class ValidatorAdapter(private val impl: IValidator) : IValidator {
    // Delegate all interface methods to the wrapped implementation
    override fun name(): String = impl.name()

    override fun version(): String = impl.version()

    override fun initialize() = impl.initialize()

    override fun shutdown() = impl.shutdown()

    override fun description(): String = impl.description()

    override fun author(): String = impl.author()

    override suspend fun validate(result: ExtractedDocument, config: ExtractionConfig): Unit {
        return impl.validate(result, config)
    }

    override fun shouldValidate(result: ExtractedDocument, config: ExtractionConfig): Boolean {
        return impl.shouldValidate(result, config)
    }

    override fun priority(): Int {
        return impl.priority()
    }
}
