// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1600e5fcfaf87c1ca29bc621df9103e2271f97ba4a3645d3d75b46616494e516
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Properties for anchored drawings.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class AnchorPropertiesBuilder {

    private boolean behindDoc = false;
    private boolean layoutInCell = false;
    private Optional<Long> relativeHeight = Optional.empty();
    private Optional<String> positionH = Optional.empty();
    private Optional<String> positionV = Optional.empty();
    private String wrapType = "";

    /** Sets the behindDoc field. */
    @com.fasterxml.jackson.annotation.JsonProperty("behind_doc")
    public AnchorPropertiesBuilder withBehindDoc(final boolean value) {
        this.behindDoc = value;
        return this;
    }

    /** Sets the layoutInCell field. */
    @com.fasterxml.jackson.annotation.JsonProperty("layout_in_cell")
    public AnchorPropertiesBuilder withLayoutInCell(final boolean value) {
        this.layoutInCell = value;
        return this;
    }

    /** Sets the relativeHeight field. */
    @com.fasterxml.jackson.annotation.JsonProperty("relative_height")
    public AnchorPropertiesBuilder withRelativeHeight(final Optional<Long> value) {
        this.relativeHeight = value;
        return this;
    }

    /** Sets the positionH field. */
    @com.fasterxml.jackson.annotation.JsonProperty("position_h")
    public AnchorPropertiesBuilder withPositionH(final Optional<String> value) {
        this.positionH = value;
        return this;
    }

    /** Sets the positionV field. */
    @com.fasterxml.jackson.annotation.JsonProperty("position_v")
    public AnchorPropertiesBuilder withPositionV(final Optional<String> value) {
        this.positionV = value;
        return this;
    }

    /** Sets the wrapType field. */
    @com.fasterxml.jackson.annotation.JsonProperty("wrap_type")
    public AnchorPropertiesBuilder withWrapType(final String value) {
        this.wrapType = value;
        return this;
    }

    /** Builds the AnchorProperties instance. */
    public AnchorProperties build() {
        return new AnchorProperties(behindDoc, layoutInCell, relativeHeight.orElse(null), positionH.orElse(null),
                positionV.orElse(null), wrapType);
    }
}
