// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:be6d478772ae8083740767e37cfaedcc174225fc2168623c359ce29be6e5d268
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * A single file extracted from an archive.
 *
 * When archives (ZIP, TAR, 7Z, GZIP) are extracted with recursive extraction enabled, each processable file produces
 * its own full {@code ExtractionResult}.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ArchiveEntry(
        /** Archive-relative file path (e.g. "folder/document.pdf"). */
        String path,
        /** Detected MIME type of the file. */
        @JsonProperty("mime_type") String mimeType,
        /** Full extraction result for this file. */
        ExtractionResult result) {
}
