// DO NOT EDIT - auto-generated by alef
// alef:hash:00011923c8a2aa4a10294ed55a79684428333a2937d39a18af89de08f82149e3
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
