// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:731351c835fe5bdd1fe95c76a19bb292a78d19d3c3f4aa23a743e91a992b03b3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

/** Exception thrown when type conversion fails. */
public class ConversionErrorException extends KreuzbergRsException {
    /** Creates a new ConversionErrorException. */
    public ConversionErrorException(final String message) {
        super(2, message);
    }

    /** Creates a new ConversionErrorException with a cause. */
    public ConversionErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
