// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9ff943e189ecbb2d4531939ec177757ac35722da5b67ea9500725c04191e09a4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * dBASE field information.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DbfFieldInfo(String name, @JsonProperty("field_type") String fieldType) {
}
