// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3b171f38afe4ee8c2ba080d5d8ad8941c5a0127b22a7421f0645934b01881905
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * dBASE (DBF) file metadata.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class DbfMetadataBuilder {

    private long recordCount = 0;
    private long fieldCount = 0;
    private List<DbfFieldInfo> fields = List.of();

    /** Sets the recordCount field. */
    public DbfMetadataBuilder withRecordCount(final long value) {
        this.recordCount = value;
        return this;
    }

    /** Sets the fieldCount field. */
    public DbfMetadataBuilder withFieldCount(final long value) {
        this.fieldCount = value;
        return this;
    }

    /** Sets the fields field. */
    public DbfMetadataBuilder withFields(final List<DbfFieldInfo> value) {
        this.fields = value;
        return this;
    }

    /** Builds the DbfMetadata instance. */
    public DbfMetadata build() {
        return new DbfMetadata(recordCount, fieldCount, fields);
    }
}
