// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9e7bcbc981e083c23a7b521b17dc2a1165dd284d6a81dfbe4d62429733062456
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Image element in Djot.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DjotImage(
        /** Image source URL or path */
        String src,
        /** Alternative text */
        String alt,
        /** Optional title */
        @Nullable String title,
        /** Element attributes */
        @Nullable String attributes) {
}
