// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f7a6532fa700ab92cea4c142b9f194e9e9fd44a051db78c2815920ac6ecbce8b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Excel/spreadsheet metadata marker.
 *
 * Sheet count and sheet names are now exposed directly on Metadata as {@code sheet_count: Option&lt;usize&gt;} and
 * {@code sheet_names: Option&lt;Vec&lt;String&gt;&gt;} so that every binding (Rust, Python, Node, …) sees them at the
 * same path. This struct remains as a {@code FormatMetadata} variant tag for spreadsheet sources.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class ExcelMetadataBuilder {

    /** Builds the ExcelMetadata instance. */
    public ExcelMetadata build() {
        return new ExcelMetadata();
    }
}
