// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:71f1957d932bcc2941feb7e7809b8c732fc777d34fc70c6ae946f08d9076a9a1
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Server information response.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record InfoResponse(String version, @JsonProperty("rust_backend") boolean rustBackend) {
}
