// DO NOT EDIT - auto-generated by alef
// alef:hash:4c42d936f18e79393a3bcbbe58f4b0f0998d0c26bdf19145561ee1d3e7206604
package dev.kreuzberg;

public class IoException extends KreuzbergErrorException {
    /** Creates a new IoException with the given message. */
    public IoException(final String message) {
        super(message);
    }

    /** Creates a new IoException with the given message and cause. */
    public IoException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
