// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d931b0e483c3367c1c0de7a83dfdebecd9acf829737fc50dd03b05361153315b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Extraction result metadata.
 *
 * Contains common fields applicable to all formats, format-specific metadata via a discriminated union, and additional
 * custom fields from postprocessors.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class MetadataBuilder {

    private Optional<String> title = Optional.empty();
    private Optional<String> subject = Optional.empty();
    private Optional<List<String>> authors = Optional.empty();
    private Optional<List<String>> keywords = Optional.empty();
    private Optional<String> language = Optional.empty();
    private Optional<String> createdAt = Optional.empty();
    private Optional<String> modifiedAt = Optional.empty();
    private Optional<String> createdBy = Optional.empty();
    private Optional<String> modifiedBy = Optional.empty();
    private Optional<PageStructure> pages = Optional.empty();
    private Optional<FormatMetadata> format = Optional.empty();
    private Optional<ImagePreprocessingMetadata> imagePreprocessing = Optional.empty();
    private Optional<Object> jsonSchema = Optional.empty();
    private Optional<ErrorMetadata> error = Optional.empty();
    private Optional<Long> extractionDurationMs = Optional.empty();
    private Optional<String> category = Optional.empty();
    private Optional<List<String>> tags = Optional.empty();
    private Optional<String> documentVersion = Optional.empty();
    private Optional<String> abstractText = Optional.empty();
    private Optional<String> outputFormat = Optional.empty();
    private Optional<Long> sheetCount = Optional.empty();
    private Optional<List<String>> sheetNames = Optional.empty();
    private Map<String, Object> additional = Map.of();

    /** Sets the title field. */
    public MetadataBuilder withTitle(final Optional<String> value) {
        this.title = value;
        return this;
    }

    /** Sets the subject field. */
    public MetadataBuilder withSubject(final Optional<String> value) {
        this.subject = value;
        return this;
    }

    /** Sets the authors field. */
    public MetadataBuilder withAuthors(final Optional<List<String>> value) {
        this.authors = value;
        return this;
    }

    /** Sets the keywords field. */
    public MetadataBuilder withKeywords(final Optional<List<String>> value) {
        this.keywords = value;
        return this;
    }

    /** Sets the language field. */
    public MetadataBuilder withLanguage(final Optional<String> value) {
        this.language = value;
        return this;
    }

    /** Sets the createdAt field. */
    @com.fasterxml.jackson.annotation.JsonProperty("created_at")
    public MetadataBuilder withCreatedAt(final Optional<String> value) {
        this.createdAt = value;
        return this;
    }

    /** Sets the modifiedAt field. */
    @com.fasterxml.jackson.annotation.JsonProperty("modified_at")
    public MetadataBuilder withModifiedAt(final Optional<String> value) {
        this.modifiedAt = value;
        return this;
    }

    /** Sets the createdBy field. */
    @com.fasterxml.jackson.annotation.JsonProperty("created_by")
    public MetadataBuilder withCreatedBy(final Optional<String> value) {
        this.createdBy = value;
        return this;
    }

    /** Sets the modifiedBy field. */
    @com.fasterxml.jackson.annotation.JsonProperty("modified_by")
    public MetadataBuilder withModifiedBy(final Optional<String> value) {
        this.modifiedBy = value;
        return this;
    }

    /** Sets the pages field. */
    public MetadataBuilder withPages(final Optional<PageStructure> value) {
        this.pages = value;
        return this;
    }

    /** Sets the format field. */
    public MetadataBuilder withFormat(final Optional<FormatMetadata> value) {
        this.format = value;
        return this;
    }

    /** Sets the imagePreprocessing field. */
    @com.fasterxml.jackson.annotation.JsonProperty("image_preprocessing")
    public MetadataBuilder withImagePreprocessing(final Optional<ImagePreprocessingMetadata> value) {
        this.imagePreprocessing = value;
        return this;
    }

    /** Sets the jsonSchema field. */
    @com.fasterxml.jackson.annotation.JsonProperty("json_schema")
    public MetadataBuilder withJsonSchema(final Optional<Object> value) {
        this.jsonSchema = value;
        return this;
    }

    /** Sets the error field. */
    public MetadataBuilder withError(final Optional<ErrorMetadata> value) {
        this.error = value;
        return this;
    }

    /** Sets the extractionDurationMs field. */
    @com.fasterxml.jackson.annotation.JsonProperty("extraction_duration_ms")
    public MetadataBuilder withExtractionDurationMs(final Optional<Long> value) {
        this.extractionDurationMs = value;
        return this;
    }

    /** Sets the category field. */
    public MetadataBuilder withCategory(final Optional<String> value) {
        this.category = value;
        return this;
    }

    /** Sets the tags field. */
    public MetadataBuilder withTags(final Optional<List<String>> value) {
        this.tags = value;
        return this;
    }

    /** Sets the documentVersion field. */
    @com.fasterxml.jackson.annotation.JsonProperty("document_version")
    public MetadataBuilder withDocumentVersion(final Optional<String> value) {
        this.documentVersion = value;
        return this;
    }

    /** Sets the abstractText field. */
    @com.fasterxml.jackson.annotation.JsonProperty("abstract_text")
    public MetadataBuilder withAbstractText(final Optional<String> value) {
        this.abstractText = value;
        return this;
    }

    /** Sets the outputFormat field. */
    @com.fasterxml.jackson.annotation.JsonProperty("output_format")
    public MetadataBuilder withOutputFormat(final Optional<String> value) {
        this.outputFormat = value;
        return this;
    }

    /** Sets the sheetCount field. */
    @com.fasterxml.jackson.annotation.JsonProperty("sheet_count")
    public MetadataBuilder withSheetCount(final Optional<Long> value) {
        this.sheetCount = value;
        return this;
    }

    /** Sets the sheetNames field. */
    @com.fasterxml.jackson.annotation.JsonProperty("sheet_names")
    public MetadataBuilder withSheetNames(final Optional<List<String>> value) {
        this.sheetNames = value;
        return this;
    }

    /** Sets the additional field. */
    public MetadataBuilder withAdditional(final Map<String, Object> value) {
        this.additional = value;
        return this;
    }

    /** Builds the Metadata instance. */
    public Metadata build() {
        return new Metadata(title.orElse(null), subject.orElse(null), authors.orElse(null), keywords.orElse(null),
                language.orElse(null), createdAt.orElse(null), modifiedAt.orElse(null), createdBy.orElse(null),
                modifiedBy.orElse(null), pages.orElse(null), format.orElse(null), imagePreprocessing.orElse(null),
                jsonSchema.orElse(null), error.orElse(null), extractionDurationMs.orElse(null), category.orElse(null),
                tags.orElse(null), documentVersion.orElse(null), abstractText.orElse(null), outputFormat.orElse(null),
                sheetCount.orElse(null), sheetNames.orElse(null), additional);
    }
}
