// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a67cf1835724bd2357197b55584ef2a7035a7830afa48e03df25cde099933703
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

@JsonDeserialize(builder = OcrCacheStatsBuilder.class)
public record OcrCacheStats(@JsonProperty("total_files") long totalFiles,
        @JsonProperty("total_size_mb") double totalSizeMb) {
    public static OcrCacheStatsBuilder builder() {
        return new OcrCacheStatsBuilder();
    }
}
