// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1a9f3a67388760760609f9476ced2e3c7acac0c425a5a59612224847cbc1adcd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Document orientation detection result.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record OrientationResult(int degrees, float confidence) {
}
