// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3fe16ec643c167d426118598adb3623354bd2b7c8f06e7e3c58b310f764a961a
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

@SuppressWarnings("checkstyle:LineLength")
public class StreamReader implements AutoCloseable {
    private final MemorySegment handle;

    StreamReader(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_STREAM_READER_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free StreamReader: " + e.getMessage(), e);
            }
        }
    }
}
