// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:64c0b91c3b72bd73af6f0df691cc30047914a49529d9da2d017bd1c00ab58b2c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * Year range for bibliographic metadata.
 */
@SuppressWarnings("checkstyle:LineLength")
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record YearRange(@Nullable Integer min, @Nullable Integer max,
        @JsonInclude(JsonInclude.Include.NON_NULL) List<Integer> years) {
}
