# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0605fd9cfbce0c9f61e0ac383fe26c9ecce460fc4826a1db3468dcae1793a707
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ArchiveEntry do
  @moduledoc "A single file extracted from an archive."

  defstruct path: "",
            mime_type: "",
            result: nil
end
