# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0336260e302c26ff585c4c04aceb3a97bacbca7a5eb642e1813c88dd18ea364d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.BatchBytesItem do
  @moduledoc """
  Batch item for byte array extraction.

  Used with `batch_extract_bytes` and `batch_extract_bytes_sync`
  to represent a single item in a batch extraction job.
  """

  @typedoc "Batch item for byte array extraction."
  @type t :: %__MODULE__{
          content: binary(),
          mime_type: String.t() | nil,
          config: map() | nil
        }

  defstruct content: <<>>,
            mime_type: nil,
            config: nil
end
