# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2aa70876db291249caef7e2a16872fadb624b2104d7a088ca1880f8c5c3791ad
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.BatchFileItem do
  @moduledoc """
  Batch item for file extraction.

  Used with `batch_extract_files` and `batch_extract_files_sync`
  to represent a single file in a batch extraction job.
  """

  @typedoc "Batch item for file extraction."
  @type t :: %__MODULE__{
          path: String.t() | nil,
          config: map() | nil
        }

  defstruct path: nil,
            config: nil
end
