# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cb855b5d14d74df904faec363ef477bfae87c4666396e9baad55d6044c6a4605
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.BoundingBox do
  @moduledoc "Bounding box coordinates for element positioning."

  @typedoc "Bounding box coordinates for element positioning."
  @type t :: %__MODULE__{
          x0: float(),
          y0: float(),
          x1: float(),
          y1: float()
        }

  defstruct x0: 0.0,
            y0: 0.0,
            x1: 0.0,
            y1: 0.0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
