# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:37eec9b31bfa8b311a237c10289061f345aaa6b99c6958dda64bdba434fd19ca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkSizing do
  @moduledoc "How chunk size is measured."

  @type t :: term()

  @type characters :: :characters
  @type tokenizer :: %{type: :tokenizer, model: term(), cache_dir: term()}
end
