# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fa49f061b4922ae545a884b3557c72331bc9acf91f2b03d4dfc68363dc9f62b9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ClassificationEnrichmentConfig do
  @moduledoc "Classification enrichment knob: how to label the document."

  @typedoc "Classification enrichment knob: how to label the document."
  @type t :: %__MODULE__{
          config: map()
        }

  defstruct config: nil
end
