# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c26185e7af68ca4756f10e088470f87071eb21785e05d75acd73c4ee0d7abef9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  @typedoc "JATS contributor with role."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          role: String.t() | nil
        }

  defstruct name: nil,
            role: nil
end
