# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bab5ee3c6b66145bde0a6cc47045209956496c492d7b1f8162f5a6afca9b7670
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  defstruct name: "",
            field_type: ""
end
