# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4c69455352c6694c6639030ae0ef9d405ca032b08d85d13bed84086fcdf60c8d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  @typedoc "dBASE field information."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          field_type: String.t() | nil
        }

  defstruct name: nil,
            field_type: nil
end
