# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e265914e781acd8b39915f42004afe6e9575c6c3ac252d84448a849d2576b477
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectedBoundary do
  @moduledoc "A detected structural boundary in the text."

  defstruct byte_offset: 0,
            is_header: false
end
