# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2aa70876db291249caef7e2a16872fadb624b2104d7a088ca1880f8c5c3791ad
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.DiffLine do
  @moduledoc """
  A single line in a unified-diff hunk.

  Defined here (rather than only in `crate::diff`) so `RevisionDelta` can
  reference it unconditionally, without requiring the `diff` Cargo feature.
  `crate::diff` re-exports this type verbatim.
  """

  @typedoc "A single line in a unified-diff hunk."
  @type t :: term()

  @typedoc "Unchanged context line."
  @type context :: %{type: :context, value: String.t()}
  @typedoc "Line added in the \"after\" version."
  @type added :: %{type: :added, value: String.t()}
  @typedoc "Line removed from the \"before\" version."
  @type removed :: %{type: :removed, value: String.t()}
end
