# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:90562ffbe39bd499b87f771639ca7d49e8857d1b8450b36b684917f2508c146a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotContent do
  @moduledoc "Comprehensive Djot document structure with semantic preservation."

  defstruct plain_text: "",
            blocks: [],
            metadata: nil,
            tables: [],
            images: [],
            links: [],
            footnotes: [],
            attributes: []
end
