# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c5bda808368c40b796a81ce0e84d1f8edc2d6f4d07fc1484cd1b8bddfd467b6d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DoclingCompatResponse do
  @moduledoc "OpenWebUI \"Docling\" engine response format."

  defstruct document: "",
            status: ""
end
