# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:de6d801962dc98acae44815df4f2386e30b38bbf1e1632f51fa5b91c245ee4bc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentStructure do
  @moduledoc "Top-level structured document representation."

  defstruct nodes: [],
            source_format: "",
            relationships: [],
            node_types: []
end
