# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c77367def0c186dd0b48cb2b2bf3ff806a3fbb1ed6f53e58e23be8070ca92581
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocxMetadata do
  @moduledoc """
  Word document metadata.

  Extracted from DOCX files using shared Office Open XML metadata extraction.
  Integrates with `office_metadata` module for core/app/custom properties.
  """

  @typedoc "Word document metadata."
  @type t :: %__MODULE__{
          core_properties: map() | nil,
          app_properties: map() | nil,
          custom_properties: map() | nil
        }

  defstruct core_properties: nil,
            app_properties: nil,
            custom_properties: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
