# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a2edb97fb6c09bfa760260c3e959a1f7a3552b015ac3cfb8b3d2d4e46b864e14
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.EmailMetadata do
  @moduledoc """
  Email metadata extracted from .eml and .msg files.

  Includes sender/recipient information, message ID, and attachment list.
  """

  @typedoc "Email metadata extracted from .eml and .msg files."
  @type t :: %__MODULE__{
          from_email: String.t() | nil,
          from_name: String.t() | nil,
          to_emails: [String.t()],
          cc_emails: [String.t()],
          bcc_emails: [String.t()],
          message_id: String.t() | nil,
          attachments: [String.t()]
        }

  defstruct from_email: nil,
            from_name: nil,
            to_emails: [],
            cc_emails: [],
            bcc_emails: [],
            message_id: nil,
            attachments: []

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
