# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:985d0a216508fd99792ed41875869ccf9adc31ab431bb5e0432a7b9ffb4f0c7f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedResponse do
  @moduledoc "Embedding response containing generated embeddings."

  defstruct embeddings: [],
            model: "",
            dimensions: 0,
            count: 0
end
