# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:35527f6669ac97446d233bb9e3353f8284b5c6d8caf9c821e481807f130e26ac
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedRequest do
  @moduledoc "Embedding request for generating embeddings from text."

  defstruct texts: [],
            config: nil
end
