# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ed3cb40867508fa3eec90029cd9b152fdf7e4e73fee5fbfc634f8ffc8b09db01
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.EmbeddingConfig do
  @moduledoc """
  Embedding configuration for text chunks.

  Configures embedding generation using ONNX models via the vendored embedding engine.
  Requires the `embeddings` feature to be enabled.
  """

  @typedoc "Embedding configuration for text chunks."
  @type t :: %__MODULE__{
          model: String.t() | nil,
          normalize: boolean(),
          batch_size: non_neg_integer(),
          show_download_progress: boolean(),
          cache_dir: String.t() | nil,
          acceleration: map() | nil,
          max_embed_duration_secs: non_neg_integer() | nil
        }

  defstruct model: :preset,
            normalize: true,
            batch_size: 32,
            show_download_progress: false,
            cache_dir: nil,
            acceleration: nil,
            max_embed_duration_secs: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
