# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:39507a11f45769cd1b7de1258a4073137c80040242bd451b3479ad965e517fe5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EpubMetadata do
  @moduledoc "EPUB metadata (Dublin Core extensions)."

  defstruct coverage: "",
            dc_format: "",
            relation: "",
            source: "",
            dc_type: "",
            cover_image: ""
end
