# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e4a17520766145e761ea1662da07f7497a7f2fd19fcf9ecada67bc4a6ab85861
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EpubMetadata do
  @moduledoc "EPUB metadata (Dublin Core extensions)."

  @typedoc "EPUB metadata (Dublin Core extensions)."
  @type t :: %__MODULE__{
          coverage: String.t() | nil,
          dc_format: String.t() | nil,
          relation: String.t() | nil,
          source: String.t() | nil,
          dc_type: String.t() | nil,
          cover_image: String.t() | nil
        }

  defstruct coverage: nil,
            dc_format: nil,
            relation: nil,
            source: nil,
            dc_type: nil,
            cover_image: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
