# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:287fad381b3957c7a43d86285d13b15d426626ead595e8992131a4cf4fbe6bda
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.ExtractedImageMetadata do
  @moduledoc "Image metadata extracted from an image file."

  @typedoc "Image metadata extracted from an image file."
  @type t :: %__MODULE__{
          width: non_neg_integer(),
          height: non_neg_integer(),
          format: String.t() | nil,
          exif_data: map()
        }

  defstruct width: 0,
            height: 0,
            format: nil,
            exif_data: %{}
end
