# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ed3cb40867508fa3eec90029cd9b152fdf7e4e73fee5fbfc634f8ffc8b09db01
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.ExtractionMethod do
  @moduledoc "How the extracted text was produced."

  @typedoc "How the extracted text was produced."
  @type t :: :native | :ocr | :mixed

  @native :native
  @ocr :ocr
  @mixed :mixed

  @spec native() :: t()
  def native, do: @native
  @spec ocr() :: t()
  def ocr, do: @ocr
  @spec mixed() :: t()
  def mixed, do: @mixed
end
