# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c2a3fd9729453c7020e8a1ed4d1ef626b5f48c2861b32bca702aef7a4b1fbe9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.ExtractionDiff do
  @moduledoc "The complete diff between two `ExtractionResult` values."

  @typedoc "The complete diff between two `ExtractionResult` values."
  @type t :: %__MODULE__{
          content_diff: [map()],
          tables_added: [map()],
          tables_removed: [map()],
          tables_changed: [map()],
          metadata_changed: String.t() | nil,
          embedded_changes: map()
        }

  defstruct content_diff: [],
            tables_added: [],
            tables_removed: [],
            tables_changed: [],
            metadata_changed: nil,
            embedded_changes: nil
end
