# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b57d72e2ccacd911b2dfa6533ae8d3489829589bbf4623af44693a8182beadea
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeadingContext do
  @moduledoc "Heading context for a chunk within a Markdown document."

  defstruct headings: []
end
