# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:06ddcada78ed2466860a17bdcc3125da1f452f7d01419164197117bc43bd7a5c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeadingLevel do
  @moduledoc "A single heading in the hierarchy."

  defstruct level: 0,
            text: ""
end
