# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c2a3fd9729453c7020e8a1ed4d1ef626b5f48c2861b32bca702aef7a4b1fbe9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.HeadingContext do
  @moduledoc """
  Heading context for a chunk within a Markdown document.

  Contains the heading hierarchy from document root to this chunk's section.
  """

  @typedoc "Heading context for a chunk within a Markdown document."
  @type t :: %__MODULE__{
          headings: [map()]
        }

  defstruct headings: []
end
