# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fa49f061b4922ae545a884b3557c72331bc9acf91f2b03d4dfc68363dc9f62b9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.HeadingLevel do
  @moduledoc "A single heading in the hierarchy."

  @typedoc "A single heading in the hierarchy."
  @type t :: %__MODULE__{
          level: non_neg_integer(),
          text: String.t() | nil
        }

  defstruct level: 0,
            text: nil
end
