# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c2a3fd9729453c7020e8a1ed4d1ef626b5f48c2861b32bca702aef7a4b1fbe9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.HierarchicalBlock do
  @moduledoc """
  A text block with hierarchy level assignment.

  Represents a block of text with semantic heading information extracted from
  font size clustering and hierarchical analysis.
  """

  @typedoc "A text block with hierarchy level assignment."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          font_size: float(),
          level: String.t() | nil
        }

  defstruct text: nil,
            font_size: 0.0,
            level: nil
end
