# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:287fad381b3957c7a43d86285d13b15d426626ead595e8992131a4cf4fbe6bda
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.ImageMetadata do
  @moduledoc """
  Image metadata extracted from image files.

  Includes dimensions, format, and EXIF data.
  """

  @typedoc "Image metadata extracted from image files."
  @type t :: %__MODULE__{
          width: non_neg_integer(),
          height: non_neg_integer(),
          format: String.t() | nil,
          exif: map()
        }

  defstruct width: 0,
            height: 0,
            format: nil,
            exif: %{}

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
