# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6d89cd5ba83cde7405757b82870cac9f5eb3fc01080b830df43c9810c933291b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImageMetadataType do
  @moduledoc "Image element metadata."

  defstruct src: "",
            alt: nil,
            title: nil,
            dimensions: nil,
            image_type: :data_uri,
            attributes: []
end
