# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ed3cb40867508fa3eec90029cd9b152fdf7e4e73fee5fbfc634f8ffc8b09db01
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.InlineElement do
  @moduledoc """
  Inline element within a block.

  Represents text with formatting, links, images, etc.
  """

  @typedoc "Inline element within a block."
  @type t :: %__MODULE__{
          element_type: String.t() | nil,
          content: String.t() | nil,
          attributes: String.t() | nil,
          metadata: map() | nil
        }

  defstruct element_type: :text,
            content: nil,
            attributes: nil,
            metadata: nil
end
