# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e939c65acd0b9087465d609f7d4a63fb1e21a6ea05b1bfeb8dc1b32b54a13cf6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  @typedoc "Extracted keyword with metadata."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          score: float(),
          algorithm: String.t() | nil,
          positions: [non_neg_integer()] | nil
        }

  defstruct text: nil,
            score: 0.0,
            algorithm: :yake,
            positions: nil
end
