# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:19c64b36a144f777c394911868f3e386192c246295d27b9ff2095b5c7dd31973
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutDetectionConfig do
  @moduledoc "Layout detection configuration."

  defstruct confidence_threshold: nil,
            apply_heuristics: true,
            table_model: :tatr,
            acceleration: nil
end
