# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2dfc17c8df8ff5198f16408cc0b1ea6c2bbc15cf95b020c07bec1e1fadd46183
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LlmUsage do
  @moduledoc "Token usage and cost data for a single LLM call made during extraction."

  defstruct model: "",
            source: "",
            input_tokens: 0,
            output_tokens: 0,
            total_tokens: 0,
            estimated_cost: 0.0,
            finish_reason: ""
end
