# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fa49f061b4922ae545a884b3557c72331bc9acf91f2b03d4dfc68363dc9f62b9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.OcrBackendType do
  @moduledoc "OCR backend types."

  @typedoc "OCR backend types."
  @type t :: :tesseract | :easy_ocr | :paddle_ocr | :candle | :custom

  @tesseract :tesseract
  @easy_ocr :easy_ocr
  @paddle_ocr :paddle_ocr
  @candle :candle
  @custom :custom

  @doc "Tesseract OCR (native Rust binding)"
  @spec tesseract() :: t()
  def tesseract, do: @tesseract
  @doc "EasyOCR (Python-based, via FFI)"
  @spec easy_ocr() :: t()
  def easy_ocr, do: @easy_ocr
  @doc "PaddleOCR (Python-based, via FFI)"
  @spec paddle_ocr() :: t()
  def paddle_ocr, do: @paddle_ocr
  @doc "Candle-based VLM OCR (TrOCR, PaddleOCR-VL)."
  @spec candle() :: t()
  def candle, do: @candle
  @doc "Custom/third-party OCR backend"
  @spec custom() :: t()
  def custom, do: @custom
end
