# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a2edb97fb6c09bfa760260c3e959a1f7a3552b015ac3cfb8b3d2d4e46b864e14
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.OcrConfidence do
  @moduledoc """
  Confidence scores for an OCR element.

  Separates detection confidence (how confident that text exists at this location)
  from recognition confidence (how confident about the actual text content).
  """

  @typedoc "Confidence scores for an OCR element."
  @type t :: %__MODULE__{
          detection: float() | nil,
          recognition: float()
        }

  defstruct detection: nil,
            recognition: 0.0

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
