# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:56c7cdbeb3fd9c353dcee45b38dbf2b1c229e0a3e683ae47fbb8962334188ac4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrCacheStats do
  @moduledoc false

  defstruct total_files: 0,
            total_size_mb: 0.0
end
