# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2aa70876db291249caef7e2a16872fadb624b2104d7a088ca1880f8c5c3791ad
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PageStructure do
  @moduledoc """
  Unified page structure for documents.

  Supports different page types (PDF pages, PPTX slides, Excel sheets)
  with character offset boundaries for chunk-to-page mapping.
  """

  @typedoc "Unified page structure for documents."
  @type t :: %__MODULE__{
          total_count: non_neg_integer(),
          unit_type: String.t() | nil,
          boundaries: [map()] | nil,
          pages: [map()] | nil
        }

  defstruct total_count: 0,
            unit_type: :page,
            boundaries: nil,
            pages: nil
end
