# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cb855b5d14d74df904faec363ef477bfae87c4666396e9baad55d6044c6a4605
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PageClassificationConfig do
  @moduledoc "Configuration for the page-classification post-processor."

  @typedoc "Configuration for the page-classification post-processor."
  @type t :: %__MODULE__{
          prompt_template: String.t() | nil,
          labels: [String.t()],
          multi_label: boolean(),
          llm: map()
        }

  defstruct prompt_template: nil,
            labels: [],
            multi_label: false,
            llm: nil
end
