# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c2a3fd9729453c7020e8a1ed4d1ef626b5f48c2861b32bca702aef7a4b1fbe9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PageConfig do
  @moduledoc """
  Page extraction and tracking configuration.

  Controls how pages are extracted, tracked, and represented in the extraction results.
  When `None`, page tracking is disabled.

  Page range tracking in chunk metadata (first_page/last_page) is automatically enabled
  when page boundaries are available and chunking is configured.
  """

  @typedoc "Page extraction and tracking configuration."
  @type t :: %__MODULE__{
          extract_pages: boolean(),
          insert_page_markers: boolean(),
          marker_format: String.t() | nil
        }

  defstruct extract_pages: false,
            insert_page_markers: false,
            marker_format: "

<!-- PAGE {page_num} -->

"

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
