# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:faba9bd9cd6459916b35befc0016d7e4c4a5fff356d7aa478c51dd1ac966f022
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.PdfAnnotation do
  @moduledoc "A PDF annotation extracted from a document page."

  @typedoc "A PDF annotation extracted from a document page."
  @type t :: %__MODULE__{
          annotation_type: String.t() | nil,
          content: String.t() | nil,
          page_number: non_neg_integer(),
          bounding_box: map() | nil
        }

  defstruct annotation_type: :text,
            content: nil,
            page_number: 0,
            bounding_box: nil
end
