# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a2edb97fb6c09bfa760260c3e959a1f7a3552b015ac3cfb8b3d2d4e46b864e14
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.PostProcessorConfig do
  @moduledoc "Post-processor configuration."

  @typedoc "Post-processor configuration."
  @type t :: %__MODULE__{
          enabled: boolean(),
          enabled_processors: [String.t()] | nil,
          disabled_processors: [String.t()] | nil,
          enabled_set: [String.t()] | nil,
          disabled_set: [String.t()] | nil
        }

  defstruct enabled: true,
            enabled_processors: nil,
            disabled_processors: nil,
            enabled_set: nil,
            disabled_set: nil

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
