# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c19b6ea9fa4ac30f1e8d4d0c2113c69bd9fa57bddf45afb842fad81e32a28bd2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PptxMetadata do
  @moduledoc "PowerPoint presentation metadata."

  defstruct slide_count: 0,
            slide_names: [],
            image_count: 0,
            table_count: 0
end
