# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:24d98ae30b39ea964279976fe5fe11a6bc77bfa4beb691a5c595175778407d43
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ProcessingStage do
  @moduledoc "Processing stages for post-processors."

  @type t :: :early | :middle | :late

  @early :early
  @middle :middle
  @late :late

  @spec early() :: t()
  def early, do: @early
  @spec middle() :: t()
  def middle, do: @middle
  @spec late() :: t()
  def late, do: @late
end
