# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eeb2636272f2dec66922be5a58720f2b2e207f458d9c34cbb2d93271b340dcd4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PstMetadata do
  @moduledoc "Outlook PST archive metadata."

  defstruct message_count: 0
end
