# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cb855b5d14d74df904faec363ef477bfae87c4666396e9baad55d6044c6a4605
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.QrBoundingBox do
  @moduledoc "Pixel-space bounding box of a QR code inside its source image."

  @typedoc "Pixel-space bounding box of a QR code inside its source image."
  @type t :: %__MODULE__{
          x: non_neg_integer(),
          y: non_neg_integer(),
          width: non_neg_integer(),
          height: non_neg_integer()
        }

  defstruct x: 0,
            y: 0,
            width: 0,
            height: 0
end
