# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c2a3fd9729453c7020e8a1ed4d1ef626b5f48c2861b32bca702aef7a4b1fbe9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.RedactionTerm do
  @moduledoc """
  One user-supplied literal term to redact.

  Matched as a regex-escaped substring (so callers do not need to escape
  metacharacters themselves). Case-insensitive by default — set
  [`Self::case_sensitive`] to `true` for exact byte-match semantics.
  """

  @typedoc "One user-supplied literal term to redact."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          value: String.t() | nil,
          case_sensitive: boolean()
        }

  defstruct label: nil,
            value: nil,
            case_sensitive: false
end
