# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eec9c44b3a7cfcd5d9fd49a2197aa3b818d444a55cc68863b6c69bad344326b9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.Segment do
  @moduledoc "A text segment with its byte offset in the original document."

  @typedoc "A text segment with its byte offset in the original document."
  @type t :: %__MODULE__{
          text: String.t() | nil,
          byte_start: non_neg_integer()
        }

  defstruct text: nil,
            byte_start: 0
end
