# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5f6a515f4cee741e840244242f9d162610a0d8a3fcdf086410779e59b2395d39
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.StructuredDataType do
  @moduledoc "Structured data type classification."

  @typedoc "Structured data type classification."
  @type t :: :"json-ld" | :microdata | :rdfa

  @json_ld :"json-ld"
  @microdata :microdata
  @rd_fa :rdfa

  @doc "JSON-LD structured data"
  @spec json_ld() :: t()
  def json_ld, do: @json_ld
  @doc "Microdata"
  @spec microdata() :: t()
  def microdata, do: @microdata
  @doc "RDFa"
  @spec rd_fa() :: t()
  def rd_fa, do: @rd_fa
end
