# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0336260e302c26ff585c4c04aceb3a97bacbca7a5eb642e1813c88dd18ea364d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/sample_crate-dev/alef
defmodule Kreuzberg.StructuredDataType do
  @moduledoc "Structured data type classification."

  @typedoc "Structured data type classification."
  @type t :: :"json-ld" | :microdata | :rdfa

  @json_ld :"json-ld"
  @microdata :microdata
  @rd_fa :rdfa

  @doc "JSON-LD structured data"
  @spec json_ld() :: t()
  def json_ld, do: @json_ld
  @doc "Microdata"
  @spec microdata() :: t()
  def microdata, do: @microdata
  @doc "RDFa"
  @spec rd_fa() :: t()
  def rd_fa, do: @rd_fa
end
