# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e757eebcc34d0900ee51d7b0762322b50857973a1b1412070791abf151d1900b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredExtractionResponse do
  @moduledoc "Response from structured extraction endpoint."

  defstruct structured_output: "",
            content: "",
            mime_type: ""
end
