# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5f6a515f4cee741e840244242f9d162610a0d8a3fcdf086410779e59b2395d39
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.SummaryStrategy do
  @moduledoc "Summarisation strategy."

  @typedoc "Summarisation strategy."
  @type t :: :extractive | :abstractive

  @extractive :extractive
  @abstractive :abstractive

  @doc "Pure-Rust extractive summary (TextRank over the chunk graph). Deterministic, fast, no external service required."
  @spec extractive() :: t()
  def extractive, do: @extractive
  @doc "Abstractive summary produced by liter-llm. Requires `liter-llm` feature and a configured `LlmConfig`. Token usage is captured in [`ExtractionResult::llm_usage`](super::extraction::ExtractionResult::llm_usage)."
  @spec abstractive() :: t()
  def abstractive, do: @abstractive
end
