# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2aa70876db291249caef7e2a16872fadb624b2104d7a088ca1880f8c5c3791ad
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.SupportedFormat do
  @moduledoc """
  A supported document format entry.

  Represents a file extension and its corresponding MIME type that Kreuzberg can process.
  """

  @typedoc "A supported document format entry."
  @type t :: %__MODULE__{
          extension: String.t() | nil,
          mime_type: String.t() | nil
        }

  defstruct extension: nil,
            mime_type: nil
end
