# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e4a17520766145e761ea1662da07f7497a7f2fd19fcf9ecada67bc4a6ab85861
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TokenCounter do
  @moduledoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."

  alias Kreuzberg.Native

  defstruct [:ref]

  @typedoc "Per-category running counter for [`RedactionStrategy::TokenReplace`]."
  @type t :: %__MODULE__{ref: reference()}

  @doc "Build a default instance."
  @spec new() :: t()
  def new do
    %__MODULE__{ref: Native.tokencounter_default()}
  end

  def new() do
    ref = Native.tokencounter_new()
    %__MODULE__{ref: ref}
  end

  @doc "Allocate the next token for `category` and `original`. If the original"
  def next_token(obj, category, original) do
    Native.tokencounter_next_token(obj.ref, category, original)
  end
end
