# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c77367def0c186dd0b48cb2b2bf3ff806a3fbb1ed6f53e58e23be8070ca92581
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TranslationConfig do
  @moduledoc "Configuration for the translation post-processor."

  @typedoc "Configuration for the translation post-processor."
  @type t :: %__MODULE__{
          target_lang: String.t() | nil,
          source_lang: String.t() | nil,
          preserve_markup: boolean(),
          llm: map()
        }

  defstruct target_lang: nil,
            source_lang: nil,
            preserve_markup: false,
            llm: nil
end
