# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6e273900ce19c7622b0762a1859860b5d4a3fd0209372543c5555415f48cc0a2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.YakeParams do
  @moduledoc "YAKE-specific parameters."

  @typedoc "YAKE-specific parameters."
  @type t :: %__MODULE__{
          window_size: non_neg_integer()
        }

  defstruct window_size: 2

  defimpl Jason.Encoder do
    @doc false
    def encode(value, opts) do
      value
      |> Map.from_struct()
      |> Enum.reject(fn {_k, v} -> v == nil end)
      |> Enum.into(%{})
      |> Jason.Encoder.encode(opts)
    end
  end
end
