# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c77367def0c186dd0b48cb2b2bf3ff806a3fbb1ed6f53e58e23be8070ca92581
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.YearRange do
  @moduledoc "Year range for bibliographic metadata."

  @typedoc "Year range for bibliographic metadata."
  @type t :: %__MODULE__{
          min: non_neg_integer() | nil,
          max: non_neg_integer() | nil,
          years: [non_neg_integer()]
        }

  defstruct min: nil,
            max: nil,
            years: []
end
