# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c26185e7af68ca4756f10e088470f87071eb21785e05d75acd73c4ee0d7abef9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
defmodule Kreuzberg.YearRange do
  @moduledoc "Year range for bibliographic metadata."

  @typedoc "Year range for bibliographic metadata."
  @type t :: %__MODULE__{
          min: non_neg_integer() | nil,
          max: non_neg_integer() | nil,
          years: [non_neg_integer()]
        }

  defstruct min: nil,
            max: nil,
            years: []
end
