// DO NOT EDIT - auto-generated by alef
// alef:hash:c39dc9eda1096e5908f5d3623329d139e738e2f60f478cd21a1d3d23c7132388
package io.xberg;

/**
 * The meta-schema itself failed to compile.
 */
public class BadMetaSchemaException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new BadMetaSchemaException with the given message. */
  public BadMetaSchemaException(final String message) {
    super(message);
  }

  /** Creates a new BadMetaSchemaException with the given message and cause. */
  public BadMetaSchemaException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
