// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d63e0283476bd8f41fd1b07ab7d0bbfde196679db404e32bcf4edb1a021f1f52
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Content rendering mode for code extraction.
 *
 * Controls how extracted code content is represented in the {@code content} field
 * of {@code ExtractedDocument}.
 */
@SuppressWarnings("PMD")
public enum CodeContentMode {
    /**
     * Use TSLP semantic chunks as content (default).
     */
    Chunks("chunks"),
    /**
     * Use raw source code as content.
     */
    Raw("raw"),
    /**
     * Emit function/class headings + docstrings (no code bodies).
     */
    Structure("structure");


    /** The string value. */
    private final String value;

    CodeContentMode(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static CodeContentMode fromValue(final String value) {
        for (CodeContentMode e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown CodeContentMode value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
