// DO NOT EDIT - auto-generated by alef
// alef:hash:7b6093f244759948a70f40a504f7baff35f202ad22a2e3925f5b4946344cde9b
package io.xberg;

/**
 * Invalid configuration value.
 */
public class ConfigErrorException extends HeuristicsErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ConfigErrorException with the given message. */
    public ConfigErrorException(final String message) {
        super(message);
    }

    /** Creates a new ConfigErrorException with the given message and cause. */
    public ConfigErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
