// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:926a121ce8858da89e1c2dae78836bd02775ed955b144da6ce043a83737b8c26
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

/** Exception thrown when type conversion fails. */
@SuppressWarnings({"checkstyle:LineLength", "PMD"})
public class ConversionErrorException extends XbergRsException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ConversionErrorException. */
    public ConversionErrorException(final String message) {
        super(2, message);
    }

    /** Creates a new ConversionErrorException with a cause. */
    public ConversionErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
