// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:38239aba5298b05bb7627da7dd29f61167e18c420fcb64676bf355b0040d0a32
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * How the extracted text was produced.
 */
@SuppressWarnings("PMD")
public enum ExtractionMethod {
    /**
     * Text extracted directly from the document's native format (no OCR).
     */
    Native("native"),
    /**
     * All text was obtained via OCR (e.g. scanned image-only PDF).
     */
    Ocr("ocr"),
    /**
     * Text came from a combination of native extraction and OCR.
     */
    Mixed("mixed");


    /** The string value. */
    private final String value;

    ExtractionMethod(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ExtractionMethod fromValue(final String value) {
        for (ExtractionMethod e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown ExtractionMethod value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
