// DO NOT EDIT - auto-generated by alef
// alef:hash:38239aba5298b05bb7627da7dd29f61167e18c420fcb64676bf355b0040d0a32
package io.xberg;

/**
 * A file system or I/O operation failed. These errors always bubble up unchanged.
 */
public class IoException extends XbergErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new IoException with the given message. */
  public IoException(final String message) {
    super(message);
  }

  /** Creates a new IoException with the given message and cause. */
  public IoException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
