// DO NOT EDIT - auto-generated by alef
// alef:hash:926a121ce8858da89e1c2dae78836bd02775ed955b144da6ce043a83737b8c26
package io.xberg;

/**
 * Errors produced while loading or validating a preset file.
 */
public class LoadErrorException extends Exception {
    private static final long serialVersionUID = 1L;
    /** Creates a new LoadErrorException with the given message. */
    public LoadErrorException(final String message) {
        super(message);
    }

    /** Creates a new LoadErrorException with the given message and cause. */
    public LoadErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
