// DO NOT EDIT - auto-generated by alef
// alef:hash:0dfdfc675fa0466d5742def18462b27194b5262bca2a05f5d7a89010cf5bb3b0
package io.xberg;

/**
 * A required optional system dependency (e.g. `tesseract`) was not found.
 */
public class MissingDependencyException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new MissingDependencyException with the given message. */
    public MissingDependencyException(final String message) {
        super(message);
    }

    /** Creates a new MissingDependencyException with the given message and cause. */
    public MissingDependencyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
