// DO NOT EDIT - auto-generated by alef
// alef:hash:eb5be1c33cb28fe9cd7339926a1508239529d634524a0fcd5f530dcb435666df
package io.xberg;

/**
 * A required optional system dependency (e.g. `tesseract`) was not found.
 */
public class MissingDependencyException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new MissingDependencyException with the given message. */
    public MissingDependencyException(final String message) {
        super(message);
    }

    /** Creates a new MissingDependencyException with the given message and cause. */
    public MissingDependencyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
