// DO NOT EDIT - auto-generated by alef
// alef:hash:76dabbbc48f44358b4e72324b0f3fb0ea5555b0846c36bab986b34e87c098baf
package io.xberg;

/**
 * Document parsing failed (e.g. corrupt file, unsupported format feature).
 */
public class ParsingException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ParsingException with the given message. */
    public ParsingException(final String message) {
        super(message);
    }

    /** Creates a new ParsingException with the given message and cause. */
    public ParsingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
