// DO NOT EDIT - auto-generated by alef
// alef:hash:33cd355feac899a31cf1fb6f8a5313ff322dad245ad8c30d97279d07b63f4a51
package io.xberg;

/**
 * Document parsing failed (e.g. corrupt file, unsupported format feature).
 */
public class ParsingException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new ParsingException with the given message. */
    public ParsingException(final String message) {
        super(message);
    }

    /** Creates a new ParsingException with the given message and cause. */
    public ParsingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
