// DO NOT EDIT - auto-generated by alef
// alef:hash:49d7737c4c8395f019e87ea16ab3317aeda42281d98fd36f5ee4369a81b3e523
package io.xberg;

/**
 * The file is not valid JSON.
 */
public class ParseException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new ParseException with the given message. */
  public ParseException(final String message) {
    super(message);
  }

  /** Creates a new ParseException with the given message and cause. */
  public ParseException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
