// DO NOT EDIT - auto-generated by alef
// alef:hash:eb5be1c33cb28fe9cd7339926a1508239529d634524a0fcd5f530dcb435666df
package io.xberg;

/**
 * PDF analysis step failed (only when `heuristics-pdf` feature is active).
 */
public class PdfAnalysisErrorException extends HeuristicsErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new PdfAnalysisErrorException with the given message. */
    public PdfAnalysisErrorException(final String message) {
        super(message);
    }

    /** Creates a new PdfAnalysisErrorException with the given message and cause. */
    public PdfAnalysisErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
