// DO NOT EDIT - auto-generated by alef
// alef:hash:49d7737c4c8395f019e87ea16ab3317aeda42281d98fd36f5ee4369a81b3e523
package io.xberg;

/**
 * PDF analysis step failed (only when `heuristics-pdf` feature is active).
 */
public class PdfAnalysisErrorException extends HeuristicsErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new PdfAnalysisErrorException with the given message. */
  public PdfAnalysisErrorException(final String message) {
    super(message);
  }

  /** Creates a new PdfAnalysisErrorException with the given message and cause. */
  public PdfAnalysisErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
