// DO NOT EDIT - auto-generated by alef
// alef:hash:33cd355feac899a31cf1fb6f8a5313ff322dad245ad8c30d97279d07b63f4a51
package io.xberg;

/**
 * The reranker model or reranking pipeline returned an error.
 *
 * Since v5.0.0.
 */
public class RerankingException extends XbergErrorException {
    private static final long serialVersionUID = 1L;

    /** Creates a new RerankingException with the given message. */
    public RerankingException(final String message) {
        super(message);
    }

    /** Creates a new RerankingException with the given message and cause. */
    public RerankingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
