// DO NOT EDIT - auto-generated by alef
// alef:hash:eb5be1c33cb28fe9cd7339926a1508239529d634524a0fcd5f530dcb435666df
package io.xberg;

/**
 * Errors produced while resolving a preset against caller overrides.
 */
public class ResolveErrorException extends Exception {
    private static final long serialVersionUID = 1L;
    /** Creates a new ResolveErrorException with the given message. */
    public ResolveErrorException(final String message) {
        super(message);
    }

    /** Creates a new ResolveErrorException with the given message and cause. */
    public ResolveErrorException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
