// DO NOT EDIT - auto-generated by alef
// alef:hash:7d69f93c62f49996446ca8e109bc69aee242e943de2dc761a797a89f85d56f7c
package io.xberg;

/**
 * Errors produced while resolving a preset against caller overrides.
 */
public class ResolveErrorException extends Exception {
  private static final long serialVersionUID = 1L;
  /** Creates a new ResolveErrorException with the given message. */
  public ResolveErrorException(final String message) {
    super(message);
  }

  /** Creates a new ResolveErrorException with the given message and cause. */
  public ResolveErrorException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
