// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a8a2fb5049e2e094c83b3ad2e0f6f13f62b4fea58f71c4a4f1e331a37b4cdec3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
package io.xberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Semantic classification of a tracked change.
 */
@SuppressWarnings("PMD")
public enum RevisionKind {
    /**
     * Text or content was inserted.
     */
    Insertion("insertion"),
    /**
     * Text or content was deleted.
     */
    Deletion("deletion"),
    /**
     * Run-level formatting (font, size, colour, …) was changed.
     */
    FormatChange("format_change"),
    /**
     * A reviewer comment or annotation.
     */
    Comment("comment");


    /** The string value. */
    private final String value;

    RevisionKind(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static RevisionKind fromValue(final String value) {
        for (RevisionKind e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown RevisionKind value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
