// DO NOT EDIT - auto-generated by alef
// alef:hash:c39dc9eda1096e5908f5d3623329d139e738e2f60f478cd21a1d3d23c7132388
package io.xberg;

/**
 * The file parses as JSON but does not validate against the meta-schema.
 */
public class SchemaValidationException extends LoadErrorException {
  private static final long serialVersionUID = 1L;

  /** Creates a new SchemaValidationException with the given message. */
  public SchemaValidationException(final String message) {
    super(message);
  }

  /** Creates a new SchemaValidationException with the given message and cause. */
  public SchemaValidationException(final String message, final Throwable cause) {
    super(message, cause);
  }
}
