// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c39dc9eda1096e5908f5d3623329d139e738e2f60f478cd21a1d3d23c7132388
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

import { describe, expect, it } from "vitest";
import { extract, ExtractInput, WasmExtractionConfig, WasmAccelerationConfig, WasmCaptioningConfig, WasmChunkingConfig, WasmContentFilterConfig, WasmEmailConfig, WasmEmbeddingConfig, WasmHierarchyConfig, WasmHtmlOutputConfig, WasmImageExtractionConfig, WasmImagePreprocessingConfig, WasmKeywordConfig, WasmLanguageDetectionConfig, WasmLayoutDetectionConfig, WasmLlmConfig, WasmNerConfig, WasmOcrConfig, WasmOcrElementConfig, WasmOcrPipelineConfig, WasmOcrPipelineStage, WasmOcrQualityThresholds, WasmPageClassificationConfig, WasmPageConfig, WasmPdfConfig, WasmPostProcessorConfig, WasmRakeParams, WasmRedactionConfig, WasmRedactionPattern, WasmRedactionTerm, WasmSecurityLimits, WasmStructuredExtractionConfig, WasmSummarizationConfig, WasmSvgOptions, WasmTesseractConfig, WasmTokenReductionOptions, WasmTranscriptionConfig, WasmTranslationConfig, WasmTreeSitterConfig, WasmTreeSitterProcessConfig, WasmUrlExtractionConfig, WasmYakeParams } from "@xberg/wasm";

async function _alefE2eDecompressAndParseJson(response: Response): Promise<unknown> {
	const contentEncoding = response.headers.get("content-encoding");
	let buffer = await response.arrayBuffer();

	if (contentEncoding === "gzip") {
		const { gunzipSync } = await import("zlib");
		buffer = gunzipSync(new Uint8Array(buffer)).buffer;
	} else if (contentEncoding === "br") {
		const { brotliDecompressSync } = await import("zlib");
		buffer = brotliDecompressSync(new Uint8Array(buffer)).buffer;
	}

	const text = new TextDecoder().decode(buffer);
	return JSON.parse(text);
}

function _alefE2eText(value: unknown): string {
	return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
	if (item == null || typeof item !== "object") {
		return [_alefE2eText(item)];
	}
	const record = item as Record<string, unknown>;
	const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
	return [_alefE2eText(item), _alefE2eText(record.kind), _alefE2eText(record.name), _alefE2eText(record.source), _alefE2eText(record.alias), _alefE2eText(record.text), _alefE2eText(record.signature), itemsText];
}

function _alefE2eFormatMetadataDisplay(fm: unknown): string {
	if (fm == null) return "";
	if (typeof fm !== "object") return String(fm);
	const record = fm as Record<string, unknown>;
	const formatType = record.format_type;

	// FormatMetadata is a tagged union: { format_type: 'image', image: { format: 'PNG', ... }, ... }
	// Extract the display string based on the variant type
	if (formatType === "image" && typeof record.image === "object") {
		const imageData = record.image as Record<string, unknown>;
		if (typeof imageData.format === "string") return imageData.format;
	}

	// Fallback: return format_type variant name
	if (typeof record.format_type === "string") return record.format_type;
	return "";
}


describe("contract", () => {

	it("output_format_bytes_markdown: Tests markdown output format via bytes extraction API", async () => {
		const result = await extract((() => { const _u0 = WasmExtractionConfig.default(); _u0.config = { outputFormat: "markdown" }; _u0.data = "pdf/fake_memo.pdf"; _u0.mimeType = "application/pdf"; return _u0; })(), (() => { const _u0 = WasmExtractionConfig.default(); _u0.outputFormat = "markdown"; return _u0; })());
    expect(result.mimeType.trim()).toBe("application/pdf");
    expect(result.content.length).toBeGreaterThanOrEqual(10);
    expect((result.metadata.outputFormat ?? "").trim()).toBe("markdown");
	}, 30000);
});
