// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1f99631717adbb6df383732e347abc54e9f3b505bc233ac02f3b5c215f546325
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { describe, expect, it } from "vitest";
import { extractFile, type WasmExtractionConfig } from "kreuzberg";

function _alefE2eText(value: unknown): string {
  return value == null ? "" : String(value);
}

function _alefE2eItemTexts(item: unknown): string[] {
  if (item == null || typeof item !== "object") {
    return [_alefE2eText(item)];
  }
  const record = item as Record<string, unknown>;
  const itemsText = Array.isArray(record.items) ? record.items.map(_alefE2eText).join(" ") : "";
  return [
    _alefE2eText(item),
    _alefE2eText(record.kind),
    _alefE2eText(record.name),
    _alefE2eText(record.source),
    _alefE2eText(record.alias),
    _alefE2eText(record.text),
    _alefE2eText(record.signature),
    itemsText,
  ];
}

describe("image", () => {
  it("image_metadata_only: JPEG image to validate metadata extraction without OCR.", async () => {
    const result = await extractFile("images/example.jpg", undefined, {
      disableOcr: true,
      ocr: null,
    } as WasmExtractionConfig);
    expect(result.mimeType.trim()).toBe("image/jpeg");
    expect(result.content.length).toBeLessThanOrEqual(200);
  });

  it("image_svg_basic: SVG image extraction.", async () => {
    const result = await extractFile("xml/simple_svg.svg");
    expect(result.mimeType.trim()).toBe("image/svg+xml");
    expect(result.content.length).toBeGreaterThanOrEqual(5);
  });
});
