# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eec9c44b3a7cfcd5d9fd49a2197aa3b818d444a55cc68863b6c69bad344326b9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'embed_async_pending' do
  it 'embed_texts_async_empty_input: embed_texts_async: empty text list' do
    result = Kreuzberg.embed_texts_async([])
    expect(result.length).to eq(0)

    expect(result).not_to be_nil
  end

  it 'embed_texts_async_happy: embed_texts_async: basic async embedding' do
    result = Kreuzberg.embed_texts_async(['First', 'Second'])
    expect(result.length).to be >= 2

    expect(result).not_to be_nil
  end

  it 'embed_texts_async_preset_switch: embed_texts_async: preset override' do
    result = Kreuzberg.embed_texts_async(['Text'], {model: { 'name' => 'balanced', 'type' => 'preset' }})

    expect(result).not_to be_nil
  end
end
