# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cb855b5d14d74df904faec363ef477bfae87c4666396e9baad55d6044c6a4605
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'kreuzberg'
require 'json'
require 'spec_helper'

RSpec.describe 'post_processor_management' do
  it 'post_processors_clear: Clear all post-processors and verify list is empty' do
    Kreuzberg.clear_post_processors()

  end

  it 'post_processors_list: List all registered post-processors' do
    result = Kreuzberg.list_post_processors()

    expect(result).not_to be_nil
  end
end
