# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4c69455352c6694c6639030ae0ef9d405ca032b08d85d13bed84086fcdf60c8d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

# Change to the configured test-documents directory so that fixture file paths like
# "pdf/fake_memo.pdf" resolve correctly when running rspec from e2e/ruby/.
# spec_helper.rb lives in e2e/ruby/spec/; the fixtures dir resolves three directories up.
_test_documents = File.expand_path('../../../test_documents', __dir__)
Dir.chdir(_test_documents) if Dir.exist?(_test_documents)
