# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:eb5be1c33cb28fe9cd7339926a1508239529d634524a0fcd5f530dcb435666df
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'xberg'
require 'json'

RSpec.describe 'validator_management' do
  it 'validators_clear: Clear all validators and verify list is empty' do
    Xberg.clear_validators()

  end

  it 'validators_list: List all registered validators' do
    result = Xberg.list_validators()

    expect(result).not_to be_nil
  end
end
