# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5f6a515f4cee741e840244242f9d162610a0d8a3fcdf086410779e59b2395d39
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# frozen_string_literal: true

require 'spec_helper'
require 'kreuzberg'
require 'json'

RSpec.describe 'validator_management' do
  it 'validators_clear: Clear all validators and verify list is empty' do
    Kreuzberg.clear_validators()

  end

  it 'validators_list: List all registered validators' do
    result = Kreuzberg.list_validators()

    expect(result).not_to be_nil
  end
end
