// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e4a17520766145e761ea1662da07f7497a7f2fd19fcf9ecada67bc4a6ab85861
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'package:kreuzberg/kreuzberg.dart';
import 'package:kreuzberg/src/kreuzberg_bridge_generated/frb_generated.dart' show RustLib;
import 'dart:convert';

// E2e tests for category: batch

String _alefE2eText(Object? value) {
  if (value == null) return '';
  // Check if it's an enum by examining its toString representation.
  final str = value.toString();
  if (str.contains('.')) {
    // Enum.toString() returns 'EnumName.variantName'. Extract the variant name.
    final parts = str.split('.');
    if (parts.length == 2) {
      final variantName = parts[1];
      // Convert camelCase variant names to snake_case for serde compatibility.
      // E.g. 'toolCalls' -> 'tool_calls', 'stop' -> 'stop'.
      return _camelToSnake(variantName);
    }
  }
  return str;
}

String _camelToSnake(String camel) {
  final buffer = StringBuffer();
  for (int i = 0; i < camel.length; i++) {
    final char = camel[i];
    if (char.contains(RegExp(r'[A-Z]'))) {
      if (i > 0) buffer.write('_');
      buffer.write(char.toLowerCase());
    } else {
      buffer.write(char);
    }
  }
  return buffer.toString();
}

void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  tearDownAll(() async {
    RustLib.dispose();
  });

  test('Extract text from multiple files asynchronously', () async {
    final paths = (jsonDecode(r'[{"path":"pdf/fake_memo.pdf"},{"path":"text/fake_text.txt"}]') as List<dynamic>).cast<Map<String, dynamic>>();
    final result = await KreuzbergBridge.batchExtractFiles(paths);
  });

  test('batch_extract_file async nonexistent', () async {
    final paths = (jsonDecode(r'[{"path":"/nonexistent/a.pdf"}]') as List<dynamic>).cast<Map<String, dynamic>>();
    final result = await KreuzbergBridge.batchExtractFiles(paths);
  });

  test('batch_extract_file_sync nonexistent', () async {
    final paths = (jsonDecode(r'[{"path":"/nonexistent/a.pdf"},{"path":"/nonexistent/b.txt"}]') as List<dynamic>).cast<Map<String, dynamic>>();
    final result = await KreuzbergBridge.batchExtractFilesSync(paths);
  });

  test('batch_extract_file_sync mixed', () async {
    final paths = (jsonDecode(r'[{"path":"text/plain.txt"},{"path":"/nonexistent/missing.pdf"}]') as List<dynamic>).cast<Map<String, dynamic>>();
    final result = await KreuzbergBridge.batchExtractFilesSync(paths);
  });

  test('Extract text from multiple files synchronously', () async {
    final paths = (jsonDecode(r'[{"path":"pdf/fake_memo.pdf"},{"path":"text/fake_text.txt"}]') as List<dynamic>).cast<Map<String, dynamic>>();
    final result = await KreuzbergBridge.batchExtractFilesSync(paths);
  });

}
