// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:e939c65acd0b9087465d609f7d4a63fb1e21a6ea05b1bfeb8dc1b32b54a13cf6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: embedding_backend_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_EmbeddingBackendsClear(t *testing.T) {
	// Clear all embedding backends and verify list is empty
	_ = kreuzberg.ClearEmbeddingBackends()
}

func Test_EmbeddingBackendsList(t *testing.T) {
	// List all registered embedding backends
	_, err := kreuzberg.ListEmbeddingBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
