// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c77367def0c186dd0b48cb2b2bf3ff806a3fbb1ed6f53e58e23be8070ca92581
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef

// E2e tests for category: post_processor_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_PostProcessorsClear(t *testing.T) {
	// Clear all post-processors and verify list is empty
	_ = kreuzberg.ClearPostProcessors()
}

func Test_PostProcessorsList(t *testing.T) {
	// List all registered post-processors
	_, err := kreuzberg.ListPostProcessors()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
