// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4c69455352c6694c6639030ae0ef9d405ca032b08d85d13bed84086fcdf60c8d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: post_processor_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_PostProcessorsClear(t *testing.T) {
	// Clear all post-processors and verify list is empty
	_ = kreuzberg.ClearPostProcessors()
}

func Test_PostProcessorsList(t *testing.T) {
	// List all registered post-processors
	_, err := kreuzberg.ListPostProcessors()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
