// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cb855b5d14d74df904faec363ef477bfae87c4666396e9baad55d6044c6a4605
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: registry_operations
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_ExtensionsDocx(t *testing.T) {
	// Get file extensions for DOCX MIME type
	_, err := kreuzberg.GetExtensionsForMime(`application/vnd.openxmlformats-officedocument.wordprocessingml.document`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ExtensionsHtml(t *testing.T) {
	// Get file extensions for HTML MIME type
	_, err := kreuzberg.GetExtensionsForMime(`text/html`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}

func Test_ExtensionsPdf(t *testing.T) {
	// Get file extensions for PDF MIME type
	_, err := kreuzberg.GetExtensionsForMime(`application/pdf`)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
