// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5c2a3fd9729453c7020e8a1ed4d1ef626b5f48c2861b32bca702aef7a4b1fbe9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: renderer_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_RenderersClear(t *testing.T) {
	// Clear all renderers and verify list is empty
	_ = kreuzberg.ClearRenderers()
}

func Test_RenderersList(t *testing.T) {
	// List all registered renderers
	_, err := kreuzberg.ListRenderers()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
