// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c26185e7af68ca4756f10e088470f87071eb21785e05d75acd73c4ee0d7abef9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: renderer_management
package e2e_test

import (
	"testing"

	kreuzberg "github.com/kreuzberg-dev/kreuzberg/v5"
)

func Test_RenderersClear(t *testing.T) {
	// Clear all renderers and verify list is empty
	_ = kreuzberg.ClearRenderers()
}

func Test_RenderersList(t *testing.T) {
	// List all registered renderers
	_, err := kreuzberg.ListRenderers()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
