// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:52d810dddba1010b606994310ce2a05f1937641c736814d217688096779f4320
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: summarization
package e2e_test

import (
	"encoding/json"
	"strings"
	"testing"

	xberg "github.com/xberg-io/xberg"
)

func Test_SummarizationExtractiveSmoke(t *testing.T) {
	// TextRank extractive summary over a multi-paragraph plain text document. Pure-Rust, deterministic, no external services required.
	var config xberg.ExtractionConfig
	if err := json.Unmarshal([]byte(`{"summarization":{"max_tokens":80,"strategy":"extractive"}}`), &config); err != nil {
		t.Fatalf("config parse failed: %v", err)
	}
	result, err := xberg.ExtractFileSync(`text/book_war_and_peace_1p.txt`, nil, config)
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
	if strings.TrimSpace(string(result.MimeType)) != `text/plain` {
		t.Errorf("equals mismatch: got %v", result.MimeType)
	}
	if len(result.Summary.Text) == 0 {
		t.Errorf("expected non-empty value")
	}
	if strings.TrimSpace(string(result.Summary.Strategy)) != `extractive` {
		t.Errorf("equals mismatch: got %v", result.Summary.Strategy)
	}
}
