// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:33cd355feac899a31cf1fb6f8a5313ff322dad245ad8c30d97279d07b63f4a51
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: tokenizer_backend_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg"
)

func Test_TokenizerBackendsClear(t *testing.T) {
	// Clear all tokenizer backends and verify list is empty
	_ = xberg.ClearTokenizerBackends()
}

func Test_TokenizerBackendsList(t *testing.T) {
	// List all registered tokenizer backends
	_, err := xberg.ListTokenizerBackends()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
