// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:76dabbbc48f44358b4e72324b0f3fb0ea5555b0846c36bab986b34e87c098baf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code

// E2e tests for category: validator_management
package e2e_test

import (
	"testing"

	xberg "github.com/xberg-io/xberg"
)

func Test_ValidatorsClear(t *testing.T) {
	// Clear all validators and verify list is empty
	_ = xberg.ClearValidators()
}

func Test_ValidatorsList(t *testing.T) {
	// List all registered validators
	_, err := xberg.ListValidators()
	if err != nil {
		t.Fatalf("call failed: %v", err)
	}
}
